### ISSUE TITLE
Scroll position issue

### ISSUE THREAD

**Issue by Adrastos** [MohammadYounes/AlertifyJS#100]
Hi,

First of all, thanks for this great application!

I've seen the confirm dialog restores the scroll position after it's been closed. The thing is, if I change the scroll position programmatically in the callback, it is moved again by Alertify.

For example:
(initial position of the scroll: bottom)
```javascript
alertify.confirm('Confirmation?', function() {
   $('html, body').scrollTop(0); // Moves scroll to top
});
```
This causes to scroll to top after pressing the Ok button, but alertify resets the position back to the initial bottom position.

How can I prevent Alertify to reset the scroll position?

Thanks!

**Comment by MohammadYounes** [comment]
Hi,

The scroll position is saved upon showing the dialog and gets restored once the show animation is complete, this is done to prevent document jumping (specifically in Safari).

I tried your example, the document is scrolled to the top when pressing OK. it wasn't reset to bottom!

Would you describe the exact behavior you are trying to do ?

Thanks!

**Comment by MohammadYounes** [comment]
Might be due to `maintainFocus` option which returns focus to the last active element (the one triggering the dialog). This is a global setting and it's `on` by default. 

Simply use `alertify.defaults.maintainFocus = false` to disable it.

**Comment by Adrastos** [comment]
Mohammad, thank you. I managed to fix it with your help.

2016-04-21 13:16 GMT+02:00 Mohammad Younes <notifications@github.com>:

**Comment by MohammadYounes** [comment]
Thanks for the feedback!

**Comment by IsaacMujica** [comment]
Mohammad, thanks a lot bro!!!

**Comment by prog2akralogic** [comment]
it works properly with Chrome
