### ISSUE TITLE
onshow not firing when Confirm opening for the first time

### ISSUE THREAD

**Issue by AloeDream** [MohammadYounes/AlertifyJS#102]
Hi, I have a button with onclick
Having this code inside to open Confirm box:
```js
alertify.confirm("Add Account Group", alertTemplate, function () {
                    	$dom.groupNameInput.select();
                    }, function () { $dom.groupNameInput.val(''); }).set('labels', { ok: 'Yes', cancel: 'No' }).set('transition', null).set({ onshow: function() {
                    	var combo = $("#groupTypeInput").kendoComboBox(
							{
								valuePrimitive: true,
								dataTextField: "Name",
								dataValueField: "Id"
							});
                    	kendo.bind(combo, availableTypes());
                    } }).showModal();
```
_groupTypeInput_ element is a <input> element described in alertTemplate string variable.

The problem is, onshow event handler not executing first time dialog opens, but executes when opening Confirm for the second time.

How can I solve this?

**Comment by AloeDream** [comment]
Ah, sorry, wasn't paying attention that setting onshow shoud be separate from calling actual Confirm.

**Comment by MohammadYounes** [comment]
This is due to showing the dialog prior to setting the delegate. you may switch to `onfocus` callback or grab the dialog instance using the parameter-less constructor, set the options, then show the dialog.


```js
alertify.confirm().set({
'labels', { ok: 'Yes', cancel: 'No' },
'transition', null,
'onshow': function() {
  var combo = $("#groupTypeInput").kendoComboBox({
    valuePrimitive: true,
    dataTextField: "Name",
    dataValueField: "Id"
  });
  kendo.bind(combo, availableTypes());
}});

alertify.confirm(
  "Add Account Group", 
  alertTemplate,
  function () { $dom.groupNameInput.select(); },
  function () { $dom.groupNameInput.val(''); }
).showModal();
```

If these defaults are shared across all dialogs, you can change the [defaults](http://alertifyjs.com/guide.html):
```js
alertify.defaults.transition = null;
alertify.defaults.glossary.ok = 'Yes';
alertify.defaults.glossary.cancel = 'No';
```

**Comment by MohammadYounes** [comment]
Was finishing up when you closed this :)

**Comment by MohammadYounes** [comment]
Another option is to create custom dialog inherited from confirm and use `onshow` hook, see [dialog factory](http://alertifyjs.com/factory.html)

**Comment by AloeDream** [comment]
@MohammadYounes thanks!
