### ISSUE TITLE
Downloadable zip does not include .message or .notify

### ISSUE THREAD

**Issue by skytreader** [MohammadYounes/AlertifyJS#103]
I got alertify by donwloading the zip and it seems that the version in that zip does not have `alertify.message` or `alertify.notify`. Browser says they are undefined.

**Comment by MohammadYounes** [comment]
Just to be 100% sure I downloaded/tested the zip file and it works just fine! You may wanna re-check your configuration.

**Comment by skytreader** [comment]
Ack. A little digging through my history and various downloads (good thing I work from more than one computer) and what seems to have happened is I downloaded my zip file from alertifyjs.org, at v1.0.10, while the one from alertifyjs.com is at 1.6.1.

I kept reconstructing my set-up from the alertifyjs.org zip which led me to conclude that the script in the zip file is faulty.

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
