### ISSUE TITLE
Minor spelling issues on factory page @ http://alertifyjs.com/factory.html

### ISSUE THREAD

**Issue by robotfood** [MohammadYounes/AlertifyJS#104]
// this.elements.footer         ==> Dialog footer div
// this.elements.resizeHandle   ==> Dialog **rezie** handle div            
            
// Dialog commands (Pin/Maximize/Close)
// this.elements.commands           ==> Object **conatining** dialog command buttons references
// this.elements.commands.container ==> Root commands div
// this.elements.commands.pin       ==> Pin command button

**Comment by MohammadYounes** [comment]
Thanks!
