### ISSUE TITLE
Feature Request: Generate Events, or define callback events

### ISSUE THREAD

**Issue by asheshv** [MohammadYounes/AlertifyJS#105]
We use the alertify dialogs a lot.

We would like to certain operation, whenever the alertify dialog resize.
At the moment, there is not way to find out such operation, unless creating an background observer, which I feel is too much for such operation.

Generating event, or calling callbacks during such operations will be good addition.

Thanks for the great product.

**Comment by MohammadYounes** [comment]
Thanks, I'll add this in the next minor version.

**Comment by asheshv** [comment]
Thanks!

**Comment by MohammadYounes** [comment]
The following are available as of 1.7.0:

* `onmove`: Gets or sets a function to invoke when the dialog is about to move.
* `onmoved`: Gets or sets a function to invoke once the dialog has been moved.
* `onresize`: Gets or sets a function to invoke when the dialog is about to resize.
* `onresized`: Gets or sets a function to invoke once the dialog has been resized.
* `onmaximize`: Gets or sets a function to invoke when the dialog is about to maximize.
* `onmaximized`: Gets or sets a function to invoke once the dialog has been maximized.
* `onrestore`: Gets or sets a function to invoke when a maximized dialog is about to restore.
* `onrestored`: Gets or sets a function to invoke once a maximized dialog has been restored.

**Comment by asheshv** [comment]
Thanks - buddy!
That was fast!
