### ISSUE TITLE
alertify.prompt() default value not resetting

### ISSUE THREAD

**Issue by avlcodemonkey** [MohammadYounes/AlertifyJS#106]
Is there a way to force the value of the input in a prompt to reset to the default every time the prompt is shown?

For example, on http://alertifyjs.com/prompt.html, I run the default example and the prompt input has the value `Prompt Value`.  I type 'Test' into the input on the prompt.  Then I cancel the prompt.  The next time I hit `Run` the prompt opens with the input value already set to 'Test'.  I would expect the input to be set to `Prompt Value` instead.  Is this by design or a bug?  And, if it is by design, can you suggest a way to force that value to reset each time the prompt opens?

Thanks.

**Comment by MohammadYounes** [comment]
It's a bug, since cancel does not update the prompt internal value. The next time you show the dialog with the same default, no change is detected, thus the input field value is not updated.

**Comment by MohammadYounes** [comment]
Fix released in [1.7.1](https://github.com/MohammadYounes/AlertifyJS/tree/1.7.1) 

Thanks!
