### ISSUE TITLE
Identify Button

### ISSUE THREAD

**Issue by standus** [MohammadYounes/AlertifyJS#107]
Hi,
I have more submit buttons on form. Form has onsubmit event which call alertifyJS.
How to identify which button submited form?

**Comment by MohammadYounes** [comment]
Hi,

From what I understand, [this answers](http://stackoverflow.com/questions/2066162/how-can-i-get-the-button-that-caused-the-submit-from-the-form-submit-event) your question.

If not feel free to re-open.

Thanks!

**Comment by standus** [comment]
Sorry my question was not accurate.
When I submit any button it is not send it in the _POST argument.

**Comment by MohammadYounes** [comment]
Give it a name, the clicked button name would appear in your post collection.

**Comment by standus** [comment]
Sure, I already have it, but button is not in _POST array in PHP.

**Comment by MohammadYounes** [comment]
Strange! Try the below example: 

```php
<!DOCTYPE HTML>
<html>  
<body>
<form method="post"> 
  <input type="submit" name="first_button" value="first button">
  <input type="submit" name="second_button" value="second button">
  <input type="submit" name="third_button" value="third button">
</form>
<hr/>
<?php 
 if(isset($_POST["first_button"])) {
     echo "First Button made the post";
 }else if(isset($_POST["second_button"])){
     echo "Second Button made the post";
 }else if(isset($_POST["third_button"])){
     echo "Third Button made the post";
 }
?>
</body>
</html>
```

**Comment by standus** [comment]
Dont say strange. I see that you dont understand what I am talking about.
1. create this function:
function confirmDialog(elem,text)
{
    event.preventDefault();
    if(alertify) {
        alertify.confirm(text, function(e){
            if (e) {
                if(elem.tagName==='A') {
                    window.location = elem.href;
                }
                else if(elem.tagName==='FORM') {
                    elem.submit();
                }
                return true;
            }
            else {
                //alertify.error("Category not saved.");
                return false;
            }
        }).setting({'title':'Title',transition:'zoom','labels':{ 'ok':'OK', 'cancel': 'Cancel'}});
    }
}
2.
Use form like this:
<form method="post" action="" name="clearform" onsubmit="return confirmDialog(this,'Confirm question');">
3.
change submit INPUTs for BUTTONs

Whe I process $_POST over PHP used button is not in _POST array.

**Comment by MohammadYounes** [comment]
You are performing a manual submit `elem.submit()`, which takes us back to the [SO answer](http://stackoverflow.com/questions/2066162/how-can-i-get-the-button-that-caused-the-submit-from-the-form-submit-event) I mentioned in my previous comment!

**Comment by standus** [comment]
OK, this is my universal dialog. Exists any way how to send submit form with some button with this model?

**Comment by MohammadYounes** [comment]
Attach an event handler to your buttons that sets a hidden field value identifying the button, then read it on the server.

Moreover, `onok` handler will always receive a `closeEvent` object, so your condition `if (e) {` will always evaluate to `true`.

You may join me here https://gitter.im/MohammadYounes/AlertifyJS
