### ISSUE TITLE
How to custom "alertify commands" color to white?

### ISSUE THREAD

**Issue by thearabbit** [MohammadYounes/AlertifyJS#110]
I would like to custom `alertify commands` color to `white`.
Please help me.

**Comment by MohammadYounes** [comment]
I used an [embedded base64 images](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/less/alertify.less#L74), you can easily replace them with your own. Here is the actual images:

- close: ![close](https://cloud.githubusercontent.com/assets/4712046/16499083/7df37824-3f07-11e6-88ec-f474df9faf8f.png)
- maximize: ![maximize](https://cloud.githubusercontent.com/assets/4712046/16499085/7df75836-3f07-11e6-8cc3-73c7be7d0413.png)
- restore: ![restore](https://cloud.githubusercontent.com/assets/4712046/16499087/7dfa01b2-3f07-11e6-8f66-f76ac5804d86.png)
- pin: ![pin](https://cloud.githubusercontent.com/assets/4712046/16499086/7df889ae-3f07-11e6-80b1-ebdbcadffa27.png)
- unpin: ![unpin](https://cloud.githubusercontent.com/assets/4712046/16499084/7df4583e-3f07-11e6-8121-ae8336000af4.png)

**Comment by thearabbit** [comment]
Thanks for your reply, where I find the embedded base64 image?

**Comment by MohammadYounes** [comment]
I already included a reference to [one of the them](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/less/alertify.less#L74), simply search for background-image

**Comment by thearabbit** [comment]
Yes, but I want to find these images (white color).

**Comment by MohammadYounes** [comment]
Here they are in white color [commands.zip](https://github.com/MohammadYounes/AlertifyJS/files/343940/commands.zip)

**Comment by thearabbit** [comment]
Thanks again.
