### ISSUE TITLE
Page/body shifting when confirmation dialog is shown.

### ISSUE THREAD

**Issue by kyletinsley** [MohammadYounes/AlertifyJS#112]
On any document where the browser's scrollbar is visible, the content shifts when an confirmation dialog is shown.  This seems to be due to the fact that "ajs-no-overflow" is setting overflow to hidden on the body.  However, this shifting looks very bad.  How can I prevent the shifting?  I'm experiencing this behavior on Chrome and IE (Windows 10) on any page where the body's scrollbar is visible (like http://alertifyjs.com/confirm.html)

Thank you!

**Comment by MohammadYounes** [comment]
Will add, for the time being you can do the following:

```js
// its preferred to measure scrollbar width (see https://davidwalsh.name/detect-scrollbar-width)
var scrollbarWidth = '?'; 
var originalBodyPadding = '?';

// add padding right to the body when showing the dialog 
'onshow': function(){ 
  document.body.style.paddingRight = originalBodyPadding  + scrollbarWidth;
}
// remove the added padding when showing the dialog is closed.
'onclose': function(){ 
  document.body.style.paddingRight = originalBodyPadding;
}
```
Thanks!

**Comment by MohammadYounes** [comment]
Closing this in favor of #114 (see https://github.com/MohammadYounes/AlertifyJS/issues/114#issuecomment-235844326)

**Comment by MohammadYounes** [comment]
@kyletinsley  As of 1.8.0 you can use `alertify.defaults.preventBodyShift = true` to fix the scrollbar when showing a modal dialog.

Thanks!
