### ISSUE TITLE
confirm, don´t stop the execution 

### ISSUE THREAD

**Issue by joserri** [MohammadYounes/AlertifyJS#113]
Why `alertify.confirm`, don´t wait for the response of the user selection OK or CANCEL? It continue the executation of the script.

in this example the execution script stop at the confirm of javascript, waiting for the user selection, but the `alertify.confirm` show then windows and don´t stop the execution waiting for user selection...
```js
$('#formName').validate({
    submitHandler: function(){
				if($('#lente_OD').val()!=''){
				     alertify.confirm('TITLE', 'MESSAGE', 
				     function(){$('#edeTaloOD').val('s');}
		                    ,function(){alertify.error('Cancel');});
				}
				if($('#lente_OD').val()!=''){
				   var confiTOD=confirm("MESSAGE?");
    				   if (confiTOD){
    					$('#edeTaloOD').val('s');
    				}
	........

});
```

**Comment by MohammadYounes** [comment]
Javascript is none-blocking, meaning its impossible to stop the execution.

 The only way to do this is via a callback,  and that's why AlertifyJS provides you with `onok` and `oncancel` callbacks. 

Thanks!

> #91
