### ISSUE TITLE
something that i do not know happend when i used the alertify

### ISSUE THREAD

**Issue by wuzhiqiang0816** [MohammadYounes/AlertifyJS#116]
I found a seriously question, when i used alertify in my web project. alertify's 'confirm' or 'alert' method of the current page has worked, I switched to other pages, for there will be fleeting,in other words 'confirm' or 'alert' will work again, I have no idea how to solve this.
maybe, the reason why This problem has occurred is that alertify has a conflict with other javascript`s files.for example: bootstrap

**Comment by MohammadYounes** [comment]
I don't think this is the case, may be an incorrect reference or a missing include ?

**Comment by wuzhiqiang0816** [comment]
Firstly ,thank you for your reply.my english is not good .I sinerely hope you could give me a hand on the issue,but  i do not know how to describe it.oh,god!it is so terrible.   In my web project ,some javascript files was imported. laypage(pagination tool),bootstrap,alertify. for this question,should  i analyse it  from which aspect? what let alertidy's alert or confirm work again when i switch another page.

**Comment by MohammadYounes** [comment]
Join me @ https://gitter.im/MohammadYounes/AlertifyJS

**Comment by MohammadYounes** [comment]
Closing as issue was related to duplicate resource loading.
