### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by GeneralRamy** [MohammadYounes/AlertifyJS#117]
Cannot read property 'glossary' of undefined(anonymous function) 
`  alertify.defaults.glossary.title = 'أليرتفاي جي اس';
   alertify.defaults.glossary.ok = 'موافق';
    alertify.defaults.glossary.cancel = 'إلغاء';`

when trying to override defaults settings .

**Comment by MohammadYounes** [comment]
Can you provide a test case! You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started.

**Comment by GeneralRamy** [comment]
Sorry about that , it is a conflict with other library with same name :(

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
