### ISSUE TITLE
Problem with Select2

### ISSUE THREAD

**Issue by delcanda** [MohammadYounes/AlertifyJS#119]
I've tried use a Select2 plugin in content, but not working correctly.
Any idea or suggestion?
[http://codepen.io/delcanda/pen/VKkWNo?editors=0010](url)

**Comment by MohammadYounes** [comment]
First, you need to include jQuery before Select2 plugin. 

Also you are making a copy of the container html, which will not have the Select2 behavior attached. You need to either move the Select2 element inside the dialog or initialize it after it gets added to the dialog.

See http://codepen.io/anon/pen/gwYGpv with fix attached to "Alertify from div" button. 

Moreover, I added the following CSS to make the Select2 appear on top of the dialog.
```css
.select2-container {
  z-index:2016;
}
```

Hope this helps! 
Thanks.

**Comment by delcanda** [comment]
That's it! 
Thanks
