### ISSUE TITLE
onCancel event not working with onOk

### ISSUE THREAD

**Issue by Gardezi1** [MohammadYounes/AlertifyJS#122]
Hello guys, 

Thanks for the awesome package. I'm having a little bit issue. Don't know if it's an issue or there is I'm doing something wrong. I'm trying to do something when the cancel button is clicked but it is not working. Here is my code 

```
    alertify.confirm(message_to_be_displayed).set('onok' ,function (closeEvent) {
        //something being done over here,
    }, 
    'onclose' , function(){
        if($('div#contact-form div.nav-tabs-horizontal ul li.active a').text().replace('11', '') == "Individual"){
            $('div#individual_contact_modal div.modal-dialog').removeAttr('style');
        }else{
            $('div#group_contact_modal div.modal-dialog').removeAttr('style');
        }    
    });

```

Can you tell me what is it that I'm doing wrong ? Thanks

**Comment by MohammadYounes** [comment]
Hi,


[`onclose` event](http://alertifyjs.com/confirm/onclose.html) is fired when closing the dialog. You should be using [`oncancel` event](http://alertifyjs.com/confirm/oncancel.html) instead. 


Thanks!

**Comment by Gardezi1** [comment]
Hello @MohammadYounes , 

Thanks for the quick reply but I tried using the onclose event that is not working either

**Comment by MohammadYounes** [comment]
@Gardezi1 Try creating an online sample to help troubleshoot the issue.

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
