### ISSUE TITLE
Apllying MASK on a Alertify prompt

### ISSUE THREAD

**Issue by sachadee** [MohammadYounes/AlertifyJS#128]
Is there a way to applique a mask on a Alertify.js prompt ?

with Jquery MASK or others.

Thanks

**Comment by MohammadYounes** [comment]
Sure, The easiest way is to hook to the [onshow](http://alertifyjs.com/prompt/onshow)/[onclose](http://alertifyjs.com/prompt/onclose) events, find the input and apply your changes.

http://codepen.io/anon/pen/VmzWjX
