### ISSUE TITLE
Best way to suppress duplicate alerts

### ISSUE THREAD

**Issue by tnrich** [MohammadYounes/AlertifyJS#129]
Hey there,

I was just wondering what the best way to suppress duplicate toaster messages would be. Ideally toasts with the same text could be collapsed/filtered out so only 1 is shown instead of many.

Thanks!

**Comment by MohammadYounes** [comment]
Hi,

For now, I would say externally (Same answer as in #123), Which I kept open to consider such options in the next version.

Please update #123 with the use cases you have.

Thanks!

**Comment by tnrich** [comment]
Sounds good thanks Mohammad. Just to be clear your solution in #123 is
basically to use a helper function that acts external to alerting itself.

I think ideally this would be baked into the alertify function itself. I
dont imagine it should be too tough to do. We just need to have a hook that
is called before the .success(), .error(), etc methods are called. The hook
would run any necessary logic and then delegate to the original function
being called. What do you think?

**Comment by MohammadYounes** [comment]
I don't see much difference between using hooks vs an external wrapper.  I was thinking of something that is configurable, where you don't have to write any logic.

Anyway, PRs are very welcome :)
