### ISSUE TITLE
'bottom-center' position?

### ISSUE THREAD

**Issue by drmcclelland** [MohammadYounes/AlertifyJS#13]
I was wondering how I might position notifications in a 'bottom-center' position?  This works well for my mobile-device browser users.

Right now I am using PNotify to provide this functionality (PNotify refers to this as the "bottom bar" style of stack which is set using the `stack: stack_bar_bottom` option and you can see a demo of it here:  http://sciactive.com/pnotify/#stacks), but I would like to use only Alertify.

PS:   Love this library!

**Comment by marc-gist** [comment]
I'd like to also see 'center' positions (top and bottom). an easy way to modify the width would also be nice :+1:

**Comment by stoivo** [comment]
I would like to see this :+1:

**Comment by afgallo** [comment]
I'd also love to see more options for positioning alerts on the screen. "centre-screen" is a must IMHO.
Thanks for the library tho, it's really good!

**Comment by Adrastos** [comment]
+1
It would be great if alerts could be centered on screen.

**Comment by marc-gist** [comment]
+1
Or some easy way to set the dom object that the notice should position it self relative to.  I.e. main body/content screen rather than visible screen.
