### ISSUE TITLE
 I have problems with notification in a modal

### ISSUE THREAD

**Issue by AlexanderBV** [MohammadYounes/AlertifyJS#131]
Well my problem is that in my html I have a modal where there is a form and I have put a send button and there I am calling the alert
_<button type = "submit" class = "btn btn-success" onclick = "alertify.success ('Added');"> <i class = "fa fa-floppy-o" aria-hidden = "true" / I> Save Changes </   #@button>_
But it turns out that the alert is not executed. Sometimes it looks but a little to the right and barely and it is visualized #

**Comment by MohammadYounes** [comment]
Not sure I understand your issue, Can you provide an online sample ? 

 > You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started.

**Comment by AlexanderBV** [comment]
@MohammadYounes 
Well, I've created a modal with bootstrap and inside it there is a form and a send button as well and then when I click on the send button I want my alert to run, I have already proven it in different ways and not I get it and I think it is because when I hit the button send form is in the modal the page is reloaded and then my alert is not displayed
I need help, could I help by teamviewer or some social network to contact and talk?

**Comment by AlexanderBV** [comment]
@MohammadYounes 
<div class="modal fade"  id="ventana1" tabindex="-1" role="dialog">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
       
        
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">ADD PRODUCT</h4>
        </div>
        
        
        
        <div class="modal-body">
                                                                
           
           <form action="" method="" class="form-horizontal">
                                         
               <input type="hidden" name="op" value="add">
               <div class="form-group">

                   <label for="descripcionProducto" class="col-sm-2 control-label">Descripcion</label>

                   <div class="col-sm-10">
                       <input name="descripcion" type="text" class="form-control" id="descripcionProducto" placeholder="Descripcion del producto.." >
                   </div>

               </div>
               
               
               <div class="modal-footer">
                   <button type="submit" class="btn btn-success" onclick="alertify.success('Agregado');"><i class="fa fa-floppy-o" aria-hidden="true"></i> Guardar Cambios</button>
                   <a class="btn btn-info" onclick="almacen()">Limpiar</a>
                   <a  class="btn btn-danger" data-dismiss="modal">Cerrar</a> 
               </div>

           </form>

        </div>                                    
     </div>
   </div>
</div>

**Comment by MohammadYounes** [comment]
join here https://gitter.im/MohammadYounes/AlertifyJS

**Comment by MohammadYounes** [comment]
Closing as the issue was not related to AlertifyJS, But rather to how the custom app is structured.
