### ISSUE TITLE
how to use AlertifyJS as normal Modal 

### ISSUE THREAD

**Issue by badrsh** [MohammadYounes/AlertifyJS#136]
Hi 
is it possible to use AlertifyJS as normal Modal  ? ? 

I mean I only need the design and the animation not something else 
and i will put my own html form inside this modal ?

**Comment by MohammadYounes** [comment]
Hi,

Yes, see the [examples page](http://alertifyjs.com/examples.html). Such as:

* [Licesne Agreement]( http://alertifyjs.com/examples.html#license)
* [Youtube Dialog](http://alertifyjs.com/examples.html#youtube)
