### ISSUE TITLE
Multiple minimalDialog on a page: Hooks still holds on to the first instance

### ISSUE THREAD

**Issue by ChristofferJoergensen** [MohammadYounes/AlertifyJS#137]
I've previously asked about [how to have multiple minimalDialog windows on the same page](https://github.com/MohammadYounes/AlertifyJS/issues/115), and making sure content is refreshed in accordance with the new opened window.

The trick was to assign content to a variable:

    prompt_content = el.attr("prompt-content");

and then replace this trigger:

    return alertify.minimalDialog(prompt_id)
                   .set('resizable', true).resizeTo('90%', '80%');

with this:

    return alertify.minimalDialog(prompt_id, prompt_content)
                   .set('resizable', true).resizeTo('90%', '80%');

But I now find out that everything that's happening inside the hooks (`onclose`, `onshow`, etc.) is set only once, which is the first time a window is opened. So if I e.g. want to:

    hooks: {
      onshow: function() {
        console.log("Hello for the first time");
      }
    }

in the first implementation, but I want to:

    hooks: {
      onshow: function() {
        console.log("Hello for the second time");
      }
    }

in my second implementation, then the `console.log("Hello for the first time");` will be triggered both first and second time.

How do I refresh my hooks?

**Comment by MohammadYounes** [comment]
Hooks are supposed to be internal (where you need to execute some logic on different events without interfering with public events). 

Either use public event handlers or create different dialogs.

**Comment by ChristofferJoergensen** [comment]
Hi @MohammadYounes I though I was creating different dialogs. Or will the following code draw from the first instance I create, even though they are inside different functions?

```javascript
var promptNow1;
var promptNow2;

$(function() {
  return promptNow1();
});

$(function() {
  return promptNow2();
});

promptNow1 = function() {
  var promptBtn;
  promptBtn = $(".some-div-1");
  promptBtn.off("click");
  return promptBtn.click(function(e) {
    var el, prompt_content, prompt_id;
    el = $(e.currentTarget);
    prompt_id = el.attr("prompt-id");
    prompt_content = el.attr("prompt-content");
    alertify.minimalDialog || alertify.dialog('minimalDialog', function() {
      // Implemntation 1 here
    });
    return alertify.minimalDialog(prompt_id, prompt_content)
                   .set('resizable', true).resizeTo('90%', '80%');
  });
};

promptNow2 = function() {
  var promptBtn;
  promptBtn = $(".some-div-2");
  promptBtn.off("click");
  return promptBtn.click(function(e) {
    var el, prompt_content, prompt_id;
    el = $(e.currentTarget);
    prompt_id = el.attr("prompt-id");
    prompt_content = el.attr("prompt-content");
    alertify.minimalDialog || alertify.dialog('minimalDialog', function() {
      // Implemntation 2 here
    });
    return alertify.minimalDialog(prompt_id, prompt_content)
                   .set('resizable', true).resizeTo('90%', '80%');
  });
};
```

**Comment by MohammadYounes** [comment]
@ChristofferJoergensen You are creating different instances of the same dialog.

The first call to `alertify.minimalDialog || alertify.dialog('minimalDialog', function() { ...` will create the dialog, then any call to `alertify.minimalDialog(...)` will create a minimalDialog instance.

**Comment by ChristofferJoergensen** [comment]
So what would be the alternative? Assigning it to a variable? Something like e.g.:

    mydialog = alertify.minimalDialog || alertify.dialog('minimalDialog', function() { ...

followed by:

    mydialog.minimalDialog(...)

**Comment by MohammadYounes** [comment]
@ChristofferJoergensen Apologies for the later response.

This is the dialog definition function, it means, if there is no defined dialog named `minimalDialog` then define one using the provided factory function.

I don't know your exact use case, but as I mentioned earlier, either use the public events instead of internal hooks or create a different definitions:

```js
alertify.minimalDialog1 || alertify.dialog('minimalDialog1', function() { ...
```

and 

```js
alertify.minimalDialog2 || alertify.dialog('minimalDialog2', function() { ...
```

**Comment by ChristofferJoergensen** [comment]
@MohammadYounes thanks very much for that response. I hadn't thought about changing `minimalDialog`. It partially solves the issue of different dialogues being used for completely different purposes on the same page.

However, it would not solve a dialog being used for the same purpose, on different elements. Imagine that you have many buttons with the class `.some-div`:

    promptBtn = $('.some-div');
    promptBtn.click(function(e) {
      el = $(e.currentTarget);
      prompt_id = el.attr('prompt-id');
      prompt_content = el.attr("prompt-content");
      alertify.defaults.glossary.title = prompt_id;
      alertify.minimalDialog || alertify.dialog('minimalDialog', function() {
        return {
          main: function(content) {
            return this.setContent(prompt_content);
          },
          hooks: {
            onshow: function() {
              console.log(prompt_id);
    ...

`console.log(prompt_id)` would in this case output the `prompt_id`of the first `$('.some-div')` that was pushed. How would you use a public event to reference the current `el` that was pushed?

**Comment by MohammadYounes** [comment]
The same as you set `resizable`, All you need is to set it on the instance and not the definition:

```js
promptBtn = $('.some-div');
promptBtn.click(function(e) {
  el = $(e.currentTarget);
  prompt_id = el.attr('prompt-id');
  prompt_content = el.attr("prompt-content");
  alertify.defaults.glossary.title = prompt_id;
  alertify.minimalDialog || alertify.dialog('minimalDialog', function() {
    return {
      main: function(content) {
        return this.setContent(prompt_content);
      },
      ... 
  }
  return alertify.minimalDialog(prompt_id, prompt_content)
                 .set({'resizable': true, 'onshow': function(){ console.log(prompt_id); })
                 .resizeTo('90%', '80%');
...
```

**Comment by ChristofferJoergensen** [comment]
@MohammadYounes , thanks a lot, I'm very thankfull for your answers. It seems that I can fire up the `onclose`event this way, not the `onshow`. Check out this sample:

```javascript
var promptBtn;
promptBtn = $(".click-me");
promptBtn.off("click");

promptBtn.click(function(e) {
  var content, el, title;
  el = $(e.currentTarget);
  content = "Content";
  title = "Title";
  alertify.Test || alertify.dialog('Test', function() {
    return {
      main: function(title, content) {
        this.setHeader(title);
        return this.setContent(content);
      }
    };
  });
  return alertify.Test(title, content).set({
    resizable: true,
    onshow: function() {
      return console.log("onshow");
    },
    onclose: function() {
      return console.log("onclose");
    }
  }).resizeTo('97%', '75%');
});
```

I can't make any sense of that, can you?

**Comment by MohammadYounes** [comment]
Yes, I forgot. The `onshow` needs to be set before showing the dialog, either do this:

```js
  var dialog = alertify.Test()
  return dialog
     .setContent(content)
     .set({
      title: title,
      resizable: true,
      onshow: function() {
        return console.log("onshow");
      },
      onclose: function() {
        return console.log("onclose");
      }
    }).resizeTo('97%', '75%')
      .show();
```

or this:

```js
alertify.Test || alertify.dialog('Test', function() {
    return {
      main: function(title, content, onshow) {
        this.set('onshow', onshow)
        this.setHeader(title);
        return this.setContent(content);
      }
    };
});

return alertify.Test(title, content, function() {
      return console.log("onshow");
    }).set({ ...
```

**Comment by ChristofferJoergensen** [comment]
@MohammadYounes I tried out the first suggestion, but still only get the `console.log('go')` and `console.log('onclose')` in my console.

```javascript
var promptBtn;
promptBtn = $(".click-me");
promptBtn.off("click");
promptBtn.click(function(e) {
  var content, title;
  content = "Content";
  title = "Title";
  alertify.Test || alertify.dialog('Test', function() {
    return {
      main: function(title, content, onshow) {
        this.set('onshow', onshow);
        this.setHeader(title);
        return this.setContent(content);
      }
    };
  });
  return alertify.Test(title, content, function() {
    return console.log('go');
  }).set({
    title: title,
    resizable: true,
    onshow: function() {
      return console.log('onshow');
    },
    onclose: function() {
      return console.log('onclose');
    }
  }).resizeTo('97%', '75%');
});
```

On the first suggestion I get `Uncaught TypeError: alertify.Test is not a function`.

**Comment by MohammadYounes** [comment]
The idea here is to set `onshow` before actually showing the dialog, what your code does:

1. set `onshow` to `console.log('go');` 
2. show the dialog
3. set `onshow` to `console.log('onshow');`

**Comment by ChristofferJoergensen** [comment]
@MohammadYounes you are right, I removed the `onshow` function and moved the logic in before the `set`. Thanks very much for your help.
