### ISSUE TITLE
alert dialog can be hidden by some elements

### ISSUE THREAD

**Issue by landvibe** [MohammadYounes/AlertifyJS#139]
below is an example image
![image](https://cloud.githubusercontent.com/assets/3401416/24072347/80a3cd86-0c29-11e7-8464-8a3f99de5246.png)

the vertical bar is an element of [ace editor](https://ace.c9.io)

styles of the vertical bar
![image](https://cloud.githubusercontent.com/assets/3401416/24072362/b8ade464-0c29-11e7-96a1-a0ce8243b866.png)

**Comment by MohammadYounes** [comment]
Looks like a z-index issue, can you provide an online sample ?

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
