### ISSUE TITLE
How to enable/disable the buttons of the alertify dialog based on set time ?

### ISSUE THREAD

**Issue by Balaraju1** [MohammadYounes/AlertifyJS#142]
Hi ,

I have created on Alertify dialog with "Dialog factory".
I have created two buttons in the setup function as below.

setup:function() {
            return {
              buttons:[{ text: "OK", key: 27, className: "btn btn-primary" },
                       { text: "Cancel", key: 27, className: "btn btn-primary" }],
              options: { modal: 0, resizable: true }
            };
Now i want to enable/disable the button depending on the set time of the dialog.
How to enable/disable the buttons of the alertify dialog ?

Thanks

**Comment by MohammadYounes** [comment]
Hi,

Each created button will be saved with along with the button definition inside `this.__internal.buttons`, You can access the button DOM via element property `this.__internal.buttons[index].element`. 


See how the confirm dialog implements the [auto confirm](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/confirm.js#L177) feature.

Thanks!
