### ISSUE TITLE
Add Checkbox into AlertBox

### ISSUE THREAD

**Issue by BoyGent** [MohammadYounes/AlertifyJS#143]
Hi,
I would like to add checkbox into Alert dialog and need to know if check box is checked or not after closing dialog.

Could you please help me or guide me?

Thanks,
RK

**Comment by BoyGent** [comment]
Resolved -
/// invoke the custom dialog
function showConfirm(checked) {
  return alertify
    .myConfirm('test')
    .set(
     {
      'onok': function() {
      checked(document.getElementById("myCheckBox").checked);
      },
      'label': 'Close'
    });
}
showConfirm(function(checked){
console.log(checked);
});

**Comment by MohammadYounes** [comment]
Thank You!
