### ISSUE TITLE
Apply different CSS dynamically for Dialog

### ISSUE THREAD

**Issue by BoyGent** [MohammadYounes/AlertifyJS#144]
How do I apply different css for dialog since classes are the same shared for entire module? 
i.e. One ALert I need OK button center aligned with 250px min width.

Thanks for you help in advance.

**Comment by MohammadYounes** [comment]
I would recommend using the dialog factory to create a custom dialog to satisfy your requirement, see how [alert dialog](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/alert.js) is implemented.

Another way is to hook into [onshow event](http://alertifyjs.com/alert/onshow.html) and attach the class of your choice to the root element `this.elements.root` 

Also you can use the `.show` method (currently undocumented)

```
/**
 *
 * @modal      {Boolean}  Indicates whether to show this dialog as modal or not.
 * @className  {Function} Specifies a custom class name to add to the dialog.
 */
 .show(modal, className) { ... }
```
For example:

```js

alertify.alert() //get the dialog instance first
        .setContent('Sample alert') // set the content
        .show(true, 'custom-class') // show as modal with custom-class
```

Thanks.
