### ISSUE TITLE
Dropdown unable to prevent close on click Checkbox Label

### ISSUE THREAD

**Issue by seltix5** [MohammadYounes/AlertifyJS#145]
hi,
when using :
`alertify.confirm().set({'reverseButtons': true});
alertify.prompt().set({'reverseButtons': true});`
to set reverseButtons to all popups, for some reason the event to stopPropagation on dropdown click stops work.
Test page :
https://codepen.io/seltix/pen/XRPrwM

**Comment by MohammadYounes** [comment]
Hi,

Thanks for the sample, seems to be related to `body` element having `tabindex="0"`.  A quick fix would be to add `tabindex="0"` to the `label` as shown [here](https://codepen.io/MohammadYounes/pen/NjLgdP)

In the next update, I'll make tab index be added only when showing the dialog.

Thanks!

**Comment by seltix5** [comment]
hi,
wow, dint expect that, why the tabindex on the body affect the click event on the dropdown?

Btw, the fix works, thanks!

**Comment by MohammadYounes** [comment]
Not 100% sure, but seems the click event on none tab-able elements will be fired on the first tab-able element. if none found,  it will be fired on the first container that is listening on it :)

**Comment by seltix5** [comment]
weird behavior  :S thanks ^^

**Comment by MohammadYounes** [comment]
Or may be one of the other libraries are hooking into `focus`, `focusin` or `focusout` events, which gets fired before `click` event when body has `tabindex="0"`.

**Comment by seltix5** [comment]
hi,
i update the codepen to test this : https://codepen.io/seltix/pen/XRPrwM (you need to change the IF state to test this situation)
and for some reason the problem is not the tab-index directly... :/

**Comment by seltix5** [comment]
ooooopppss, ignore my previous message, it was a code error on my test, youre correct.
then the event problem must be on the bootstrap library ..
