### ISSUE TITLE
Confirm not working

### ISSUE THREAD

**Issue by PrathibhaS** [MohammadYounes/AlertifyJS#147]
While using the following statement
alertify.confirm('Confirm Message', function(){ alertify.success('Ok') }, function(){ alertify.error('Cancel')});

alertify.success('Ok') is displayed irrespective of OK or Cancel being clicked.

**Comment by MohammadYounes** [comment]
I am unable to reproduce this, Please provide a test case! You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started.

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
