### ISSUE TITLE
add clarification of external deps if any (do I need jQuery? do I need Bootstrap?)

### ISSUE THREAD

**Issue by dimkir** [MohammadYounes/AlertifyJS#148]
I was just looking for a good modal/dialog library without many deps, I found: 

 - [nakupanda/bootstrap3-dialog](https://github.com/nakupanda/bootstrap3-dialog) (which obviously requires external deps)
 - [hubspot/vex](https://github.com/HubSpot/vex) (which seems to be WIP still, but it has no external deps)

and now I found AlertifyJS ... 

would be great to know straight away from README.md if there are deps or not.

**Comment by MohammadYounes** [comment]
[Done](https://github.com/MohammadYounes/AlertifyJS/blob/master/README.md#dependencies) 😄
