### ISSUE TITLE
How to use this with VueJS?

### ISSUE THREAD

**Issue by thearabbit** [MohammadYounes/AlertifyJS#153]
I would like to try this with `VueJS Component`.
have any example to pass `Vue Component` to `Alertify Content`?

**Comment by MohammadYounes** [comment]
I haven't used VueJS. However, Alertify is concerned with the DOM element - If you are able to get a reference of the component DOM element, then it's normal JS.

I guess it is better to ask this on stackoverflow.

Thanks.
