### ISSUE TITLE
Set events for current alert/confirm only

### ISSUE THREAD

**Issue by seltix5** [MohammadYounes/AlertifyJS#154]
hi,

i search in the documentation but i dont think it is possible to set a hook just for the next call right?
For example, if i set this code :
`alertify.confirm().set({onshow:function(){ alertify.message('confirm was shown.')}});`
every time i call `alertify.confirm();` the hook will be there.

I wold like to set a event just for that specific call, for example something like this :
`alertify.confirm(html, function_success, function_error, options);`
where the options wold be the object with the "onshow" hook.

Is there a right way to do this?

For now i develope this solution :
```
alertify.confirm().set({onshow:function(e) {
    // DO SOMETHING
            
    alertify.confirm().set({onshow: undefined});
}});
        
alertify.confirm(title, html);
```

thanks!

**Comment by MohammadYounes** [comment]
Hi,

Yes, since confirm dialog is a singleton it will maintain its options. 

The solution you described is the way to go to reset `onshow` only. If you want to reset all options, simply use [`.destroy()`](http://alertifyjs.com/confirm/destroy) method.

Thanks.
