### ISSUE TITLE
Counting the Number of Notifications Present

### ISSUE THREAD

**Issue by PorkchopDonut** [MohammadYounes/AlertifyJS#155]
Good afternoon,

I really love this library and I'm using it adamantly in my own project right now.  Just out of curiosity, is there a way to count the number of currently active Notifications?  I'm trying to restrict the number of notifications that can be present at once, essentially to say that when a new notification is spawned, if there are more than ~5 notifications present, dismiss the oldest notification.

I looked through the examples on the main website and throughout the documentation for something that would assist me here but to no avail it would seem.

**Comment by MohammadYounes** [comment]
Hi

This is similar to a [previous issue](https://github.com/MohammadYounes/AlertifyJS/issues/123). Unfortunately, Current API does no expose such functionality. 

However, you can add a small wrapper to track and limit the number of spawned notifications. 

See https://codepen.io/MohammadYounes/pen/pEmdYg

Thanks.

**Comment by g-u-r-k-a-n** [comment]
Hi @MohammadYounes I came to this post when I saw notifications limited to the default 2 in a similar case. So I changed them to 10
`var t = {
            defaultMaxLogItems: 2,
            maxLogItems: 10,
}`

and the result is

![Animation](https://user-images.githubusercontent.com/55924924/209557864-a1fc88a4-f5fe-49b2-94a5-539eb3860746.gif)



I mean, I think that this setting is already exist in your library 😂

**Comment by MohammadYounes** [comment]
@g-u-r-k-a-n I think you are using a modified version. as the library doesn't have such option.

**Comment by g-u-r-k-a-n** [comment]
@MohammadYounes Oh you are right, I have had found it with unpkg section from Visual Studio IDE - Client Side Library section. So I'm removing my post above to avoid directing people to the wrong library 👍
