### ISSUE TITLE
It is possible to have a alertify alert behave like a alert browser

### ISSUE THREAD

**Issue by MikePT04** [MohammadYounes/AlertifyJS#157]
I would like to know if it's possible to have the same behaviour has the regular alerts dialog of the browser where the javascript stops when alert is showed.

I have a situation that there are multiples ajax calls and two of them when they finish, send the alertify alert dialog but the second one override the first.

Thanks

**Comment by MohammadYounes** [comment]
It's not possible to make alertify blocking in the same way as a regular alert. However, in your case you can check if the alert [is open](http://alertifyjs.com/alert/isOpen.html) or not before showing the second alert.

**Comment by MikePT04** [comment]
It's possible to have 2 alert dialog one upside The other?

Thanks

No dia segunda-feira, 9 de outubro de 2017, Mohammad Younes <
notifications@github.com> escreveu:

**Comment by MohammadYounes** [comment]
Yes, using the [dialog factory](http://alertifyjs.com/factory.html) - create another dialog based on [alert](http://alertifyjs.com/alert.html) and use it.

```js
// create a dialog based on alert
alertify.dialog('myalert', function(){ }, false, 'alert')

//invoke it 
alertify.myalert('2nd alert');
```
Thanks!

**Comment by MikePT04** [comment]
Hi Mohammad,

i've tried your solution and it works.
I can have now multiple alert dialogs at the same time.

My problem now, is how can i destroy each alert (created by the factory) when i close it?
I've tried this:

alertify.dialog('myalert', function factory() {
            return{
                hooks: {
                    onclose: function () {
                        this.destroy();
                    }
                }
            };
        }, true, 'alert');

but the browser crash after a will when i click the ok button.

Can you help me?
Thanks

**Comment by MohammadYounes** [comment]
You need to wrap `.destroy()` call inside a timeout to make it happen after transition out is complete.

```js
alertify.dialog('myalert', function factory() { 
  return { 
    hooks: { 
      onclose: function () { 
        setTimeout(this.destroy.bind(this), 1000);
      }
    }
  }  
}, true, 'alert');
```

**Comment by MikePT04** [comment]
It works.
You're awsome Mohammad!!!
