### ISSUE TITLE
Non-Singleton Modals Replicate Themselves in the DOM Instead of Being Destroyed

### ISSUE THREAD

**Issue by siegdela** [MohammadYounes/AlertifyJS#158]
When setting the transient parameter to true, modals replicate themselves in the DOM instead of being destroyed. Is there a solution to prevent these duplicate instances from accumulating?

![capture](https://user-images.githubusercontent.com/6247706/31373861-f30f50ac-ad9b-11e7-9efa-b85b1baa161e.PNG)

**Comment by MohammadYounes** [comment]
A transient dialog has its own DOM. Once you are done with the instance, call [`.destroy()`](http://alertifyjs.com/alert/destroy.html) to close the dialog, delete the associated DOM and reset all settings to its initial state.
