### ISSUE TITLE
iFrame with pdf and alertify.message

### ISSUE THREAD

**Issue by darkice32** [MohammadYounes/AlertifyJS#16]
I am very happy with alertify but I have one issue that I can't seem to fix. How can I show a message  alertify.message over a iFrame with a PDF?

**Comment by MohammadYounes** [comment]
Would you elaborate more ? can you provide a sample (You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started.)

**Comment by darkice32** [comment]
Hi,

On jsfiddle the pdf doesn't load in the iframe so here is the code to create a sample.

###################################################################
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title> - jsFiddle demo</title>
  <script type='text/javascript' src='/js/lib/dummy.js'></script>
  
  <link rel="stylesheet" type="text/css" href="/css/result-light.css">  
  <link rel="stylesheet" type="text/css" href="http://alertifyjs.com/build/css/alertify.css">    
  <link rel="stylesheet" type="text/css" href="http://alertifyjs.com/build/css/themes/default.css">    
  <script type='text/javascript' src="http://alertifyjs.com/build/alertify.js"></script>
</head>
<body>
<a href="javascript:alertify.set('notifier','position', 'top-right');alertify.success('Will stay open till clicked.', 0);void(0);">success</a>
<iframe src="http://kmmc.in/wp-content/uploads/2014/01/lesson2.pdf" width="100%" height="500px"></iframe>
</body>
</html>
###################################################################

When you click the success button the alert will be shown top-right and as you can see it will be behind the pdf instead of on top of it.

**Comment by MohammadYounes** [comment]
Thanks for the details, the issue is with windowed and windowless elements, you may try this fix http://stackoverflow.com/questions/12911428/z-index-does-not-work-in-ie7-ie8-with-pdf-in-iframe

**Comment by darkice32** [comment]
Thanks I have seen that topic and for IE, Chrome I got it working see the codepen
http://codepen.io/anon/pen/RNKpWv

But it doesn't work for firefox. Do you have any suggestions?

**Comment by MohammadYounes** [comment]
Nicely done! I tested this on FF 34.0.5 and its working fine, what version are you using ?

**Comment by darkice32** [comment]
Have you tested it within the codepen because that doesn't load the pdf I am using version 34.0 of firefox but it says there is no update...

**Comment by MohammadYounes** [comment]
Of course not! I made a local copy, it didn't work with Safari though!

![ff](https://cloud.githubusercontent.com/assets/4712046/5679701/bcb474fe-980b-11e4-9269-54335830a79e.png)


This solution worked with FF too, (Does not work with IE nor Safari): http://jsfiddle.net/y8a9z1st/

**Comment by darkice32** [comment]
It's Adobe that is the problem the build in viewer of FireFox does not have this problem. I think I am going to skip all the effort and show the notify on the left side of the screen. If I find a crossbrowser solution I will post it later. Thanks for the help btw!
