### ISSUE TITLE
How to center align Alert dialogs?

### ISSUE THREAD

**Issue by cekohli** [MohammadYounes/AlertifyJS#160]
I see that the position element can be chosen for Notifier, but there doesn't appear to be an option for Alert dialogs.

By default, the alert dialog is horizontally centered but vertically placed in the top 1/3rd of the page.  Ideally I'd like to be able to center it both horizontally and vertically.  Is there any way to accomplish this without modifying alertify.css?

**Comment by MohammadYounes** [comment]
You can make use of [`moveTo`](http://alertifyjs.com/alert/moveTo.html) method. For example:

```js
alertify.dialog('centeredAlert', function(){
  return {
    hooks:{
      'onshow': function(){
        // 1.1 to account for the 5% top & bottom margins.
        if(this.elements.dialog.clientHeight * 1.1 < window.innerHeight) {
          this.moveTo(
              window.innerWidth/2 - this.elements.dialog.clientWidth/2,
              window.innerHeight/2 - 1.1 * this.elements.dialog.clientHeight / 2
          );
        }
      }
    }
  }
}, false, 'alert');

//invoke it

alertify.centeredAlert('This is a centered alert!');
```

**Comment by cekohli** [comment]
Works perfectly.  Thanks!
