### ISSUE TITLE
How to prevent multiple ajs-dimmer

### ISSUE THREAD

**Issue by MikePT04** [MohammadYounes/AlertifyJS#161]
Hi,
when setting the transient parameter to true, each alert i open have is own `<div class="ajs-dimmer"></div>`.

Example, i call alertify.myAlert("qwerty") and then alertify.myAlert("azerty") and the screen stay more darker each time i call a new alert.

How can i prevent this multiple div?
Thanks

**Comment by MohammadYounes** [comment]
Hi,

Each dialog instance has its own dimmer. When transient, each call to a dialog creates new instance with its own DOM.  The dimmer is shown only for Modals, which are supposed to block underlying content.

You can create a custom class to hide the dimmer and apply it when showing the dialog as mentioned here in this [comment](https://github.com/MohammadYounes/AlertifyJS/issues/144#issuecomment-300579146).

Thanks.
