### ISSUE TITLE
Get it to work in Angular 4??

### ISSUE THREAD

**Issue by mastrauckas** [MohammadYounes/AlertifyJS#162]
In my `typescript` component I tried doing:
```
import * as alertify from 'alertifyjs';
```

Later inside a function that is triggered off a button click I put:
```
alertify.prompt('Prompt Message');
```

I don't get any message or error when I do this.

What exactly am I doing wrong?

**Comment by mastrauckas** [comment]
Ok, this seems to be particularly working.  It appears it's putting a block element right below my entire page and the popup is showing at the very bottom left hand side of the screen.  So I added this line but it's still not working:

```
  styleUrls: [
    './myComponent.component.scss',
    '../../../node_modules/alertifyjs/build/css/alertify.css'
  ]
```` 

They did not fix anything though.

**Comment by mastrauckas** [comment]
Added on `stackoverflow` so i will close this issue.

**Comment by MohammadYounes** [comment]
It seems the CSS is not getting served.  May be add it to your main page rather than in a component.

Thanks!

**Comment by vermadev95** [comment]
First you need to install it with
`npm install alertifyjs --save`

Next you have to import the following in the angular.json file

> "node_modules/alertifyjs/build/alertify.min.js" in the scripts array and 

> "node_modules/alertifyjs/build/css/alertify.min.css" and 

> "node_modules/alertifyjs/build/css/themes/default.min.css" in the styles array

You also need to import the alertifyjs in the component you have to use it.
Write `import * as alertify from 'alertifyjs';` at the top of the component to import it in your component.
for eg:
`alertify.minimalDialog || alertify.dialog('minimalDialog',function(){ return { main:function(content){ this.setContent(content); } }; }); alertify.minimalDialog("Minimal button-less dialog.");`
