### ISSUE TITLE
Distinguish between mouse and keyboard events for close event

### ISSUE THREAD

**Issue by odrozd** [MohammadYounes/AlertifyJS#163]
Is there a way to sense how closing event was triggered(by mouse click on button or keyboard) fro alert/confirm/prompt?

My scenario: need to allow close  of confirm dialog by clicking on button, but not allow close it by pressing Enter key.

Currently I am looking for "onclosing" event for Confirm dialog, but when I got this event I cannot sense how it was triggered.

**Comment by MohammadYounes** [comment]
I believe `window.event` would serve your need, For example:
```js
alertify.alert('Demo').set({onshow:null, onclose:function(){ 
 console.log(window.event)
}}); 
```
However, pressing <kbd>Enter</kbd> or <kbd>Esc</kbd>on a focused button would generate a mouse event with `screenX`/`screenY` set to 0.

**Comment by MohammadYounes** [comment]
I believe `window.event` would serve your need, For example:
```js
alertify.alert('Demo').set('onclose', function(){  console.log(window.event) }); 
```
However, pressing <kbd>Enter</kbd> or <kbd>Esc</kbd>on a focused button would generate a mouse event with `screenX`/`screenY` set to 0.

**Comment by odrozd** [comment]
Thx for help it seems do the trick

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
