### ISSUE TITLE
Commercial license?

### ISSUE THREAD

**Issue by yellow1912** [MohammadYounes/AlertifyJS#165]
I couldn't find a way to contact you directly, so I would like to know more about commercial license that can be used in a SaaS product (the product itself is a software platform so AlertifyJS is going to be used minimally to support the UI of the system). The link to purchase license on uplabs was not quite clear about the use in SaaS product.

**Comment by MohammadYounes** [comment]
Hi,

I believe the extended license covers your needs. Moreover, I can be reached at  Mohammad@alertifyjs.com.

Thanks.
