### ISSUE TITLE
Custom button label? 

### ISSUE THREAD

**Issue by hikarushin** [MohammadYounes/AlertifyJS#166]
Hi, I just want to know how to do the custom label of the button?

**Comment by MohammadYounes** [comment]
Hi, you can find it here http://alertifyjs.com/alert/label

**Comment by hikarushin** [comment]
This is only for Ok. What about cancel? Can I changed it?

**Comment by MohammadYounes** [comment]
That was for alert dialog, a similar option is available for confirm. See http://alertifyjs.com/confirm/labels

**Comment by mister-cairns** [comment]
I've set an alert as below, but button text not changing:

`alertify.alert('<p>Spend over £10 to receive a free gift!</p>').set('label', 'OK — back to cart');`
