### ISSUE TITLE
Don't hide page scrollbar

### ISSUE THREAD

**Issue by Wizard13** [MohammadYounes/AlertifyJS#167]
Hi!
When a dialog appears, the scrollbar of the page disappears and it appears again when dialog is dismissed. This makes the page contents shift a bit because of the change of the available width during the transition of displaying and hiding of the dialog. Is it possible for the scrollbar not to hide when the the dialog appears?

**Comment by MohammadYounes** [comment]
Hi,

Yes, simply enable [`preventBodyShift`](http://alertifyjs.com/guide.html#defaults) option.


Thanks.
