### ISSUE TITLE
Alert hides behind maximized CKEditor

### ISSUE THREAD

**Issue by Wizard13** [MohammadYounes/AlertifyJS#168]
Hi!
I'm using a WYSIWYG editor called [CKEditor ](https://ckeditor.com/ckeditor-4/)and I'd like to have an alert when user presses Save button.
If CKEditor is not maximized, alert is showing. If it's maximized, it's hidden and it it shown after I restore CKEditor.
You can see it here: [https://jsfiddle.net/90jvuvdv/](https://jsfiddle.net/90jvuvdv/)
If you press the Save icon (floppy disk), alert is shown. If you press the Maximize button (the one with the four black arrows) and then the Save button, the alert is hidden behind CKEditor and it is shown only if I press Maximize button again to restore CKEditor.
What should I alter in AlertifyJS code to make it work?

**Comment by Wizard13** [comment]
I see the problem. CKEditor uses z-index 10000, while AlertifyJS uses z-index 1981 for alerts and dimmer and 1982 for notifiers. Is there a problem if I manually change z-index of .ajs-dimmer, .ajs-modal and .alertify-notifier to something above 10000?

**Comment by Wizard13** [comment]
OK, I have added the following in my own CSS file and so far it works. If you think that there's no problem, you can close this issue.

```
.alertify .ajs-dimmer {
	z-index: 91981 !important;
}

.alertify .ajs-modal {
	z-index: 91981 !important;
}

.alertify-notifier {
	z-index: 91982 !important;
}
```

**Comment by MohammadYounes** [comment]
I don't think there will be any problem with changing the `z-index` values. 

Thanks
