### ISSUE TITLE
How can i override globally the message from confirm dialog

### ISSUE THREAD

**Issue by MikePT04** [MohammadYounes/AlertifyJS#169]
Hi, i use in my project alertify.confirm and i send the message in arguments.
I would like to know if it is possible, somehow, to make a replacement globally to the message passed in arguments.

ex:
message = "some \ntext";
alertify.confirm(message)

when it show the confirm dialog, in would like to show "some < br > text.
But i need it globally (not changing the source code) to apply the replacement. 
A extend of the confirm maybe?

Thanks

**Comment by MohammadYounes** [comment]
Hi,

Sure, you can create a dialog based on confirm and have your own logic in it. Using current confirm main function [implementation](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/confirm.js#L58-L85), you can do:
```js
alertify.dialog('myConfirm', function(){
  function transform(msg){
   return msg.replace(/\n/g,'<br/>')
  }
  return {
    main: function (_title, _message, _onok, _oncancel) {
        var title, message, onok, oncancel;
        switch (arguments.length) {
        case 1:
            message = _title;
            break;
        case 2:
            message = _title;
            onok = _message;
            break;
        case 3:
            message = _title;
            onok = _message;
            oncancel = _onok;
            break;
        case 4:
            title = _title;
            message = _message;
            onok = _onok;
            oncancel = _oncancel;
            break;
        }
        this.set('title', title);
        this.set('message', transform(message));
        this.set('onok', onok);
        this.set('oncancel', oncancel);
        return this;
    }
  }
}, false, 'confirm')
```

Then simply do:

```js
alertify.myConfirm('some \ntext')
```

Thanks!

**Comment by MikePT04** [comment]
thanks
