### ISSUE TITLE
 turbolinks compatibility for notifier

### ISSUE THREAD

**Issue by mkhairi** [MohammadYounes/AlertifyJS#17]
hi, im using alertify js with [turbolinks](https://github.com/rails/turbolinks) enable. In my crude understanding of this, when turbolinks loads a page, it destroys the div element created by notifier js.
```html
 <div class="alertify-notifier ajs-bottom ajs-right"></div>
```

**Comment by MohammadYounes** [comment]
I'll update the notifier to re-append its element the body.

**Comment by mkhairi** [comment]
i already test your latest push. 
the element still not re-append. may be we need to destroy notifier instances for each page:change.
please check and run this example on [runnable]  (http://runnable.com/VLHHlpO0_dk02R7A/alertify-with-turbolink-for-ruby-on-rails)

**Comment by MohammadYounes** [comment]
My bad! should be fixed now.

Thanks for the feedback.
