### ISSUE TITLE
custom notifier

### ISSUE THREAD

**Issue by MikePT04** [MohammadYounes/AlertifyJS#170]
Hi Mohammad,

i would like to know if it's possible to customize the notifiers, ie, can i add a icon before the message and/or a cross in the right top corner?

![image](https://user-images.githubusercontent.com/32646712/34736239-2d9b66be-f56a-11e7-9166-c3e99ca6ac72.png)

Or extend the existant?
Or create one with the factory?

Thanks for the help

**Comment by MohammadYounes** [comment]
Hi @MikePT04 

Sure, notifier accepts custom HTML messages. Moreover, the close button is already implemented and can be enabled globally via `alertify.defaults.notifier.closeButton = true`.

For example:
```js
alertify.success('<b> Some </b> <i> HTML </i> Markup!');
```
Gives you:

![image](https://user-images.githubusercontent.com/4712046/34795263-4cc415e0-f65a-11e7-9e2f-79bfcec520a3.png)


Thanks.
