### ISSUE TITLE
Confirm with function and no word-wrap or resize width

### ISSUE THREAD

**Issue by Artanis492** [MohammadYounes/AlertifyJS#171]
Hello I have written some JS to create the popup confirm alert that has a function inside of the confirm if the user clicks ok. I'd like to include some JS that would either resize the popup or make it so it doesn't word-wrap. The confirm message I am setting has carriage returns but once they appear in the pop up the returns go away and the entire message is word-wrapped. Please help me find a way around this. Here's my code:

var result = 
'LINE 1
LINE 2
LINE3';

    alertify.confirm(result, function (e) {
       if (e) {
           var jqxhr2 = apex.submit({  showWait:true});         
           apex.region("validate").refresh();
          }
    });

When the popup confirm appears it displays like:

'LINE 1 LINE 2 LINE 3'

instead of:

'LINE 1
LINE 2
LINE 3'

Any help would be greatly appreciated!

Thanks,
Derek

**Comment by Artanis492** [comment]
alertify.confirm(result, function (e) {
   if (e) {
       var jqxhr2 = apex.submit({  showWait:true});         
       apex.region("validate").refresh();
      }
});

**Comment by MohammadYounes** [comment]
Hello, 

The case you described is the exact to #169, you can find the answer [here](https://github.com/MohammadYounes/AlertifyJS/issues/169#issuecomment-354174871).

Thanks!

**Comment by MohammadYounes** [comment]
Hello, 

The case you described is the exact of #169, you can find the answer [here](https://github.com/MohammadYounes/AlertifyJS/issues/169#issuecomment-354174871).

Thanks!
