### ISSUE TITLE
div element removed after calling confirm two times with different content

### ISSUE THREAD

**Issue by mfahmawi** [MohammadYounes/AlertifyJS#173]
Assalamu alaikum,

when i call alertify.confirm(DOM Element) and then i call it again with a text as a content ex: alertify.confirm('my text').

alertifyjs delete my DOM element from the page. 
I think its because alertify move my dom element inside ajs-content, then it replace it with the text in the second call of confirm.

Please help

**Comment by MohammadYounes** [comment]
Wa Alaikum Assalaam,

You just need to preserve the DOM element and restore it when the dialog is closed.

```js
var placeholder = document.createComment('placeholder');
function confirmWithRestore(domElement){
  domElement.parentNode.replaceChild(placeholder, domElement);
  alertify.confirm(domElement).set('onclose', function(){
     // clear on close handler
     this.set('onclose', null);
    // restore domElement to its original location
     placeholder.parentNode.replaceChild(domElement, placeholder);
     // clear reference to dom element, so next show appends element to dialog.
     this.set('message', '');
  });
}
```
