### ISSUE TITLE
Return to MIT license. Sneaky Change.

### ISSUE THREAD

**Issue by advocaite** [MohammadYounes/AlertifyJS#174]
Not much changes have happen since 1.8  to the core of AlertifyJS except a sneaky change to GLPv3 this stops anyone using it under closed source websites unless they share source MIT allows us freedom to do whatever we like.

pretty bad move if you ask me to just change a license like that when it started  under MIT.

Please consider changing it back. cause I really do not think many people even noticed the change.

For now ill continue using it under MIT and cherry pick updates  or manually add them to my MIT repo based from just before 1.8.

**Comment by MohammadYounes** [comment]
Not sneaky at all, Projects change licenses all the time. 

The change was mentioned in [RELEASE NOTES](https://github.com/MohammadYounes/AlertifyJS/blob/master/RELEASENOTES.md) and reflected on the repo and website too; v1.7 and earlier are still usable under MIT. However, v1.8 and later are dual licensed under GPL3/Commercial licenses.

Thanks!
