### ISSUE TITLE
in AngularJS based app notifications appear in the very bottom of the body

### ISSUE THREAD

**Issue by Torone** [MohammadYounes/AlertifyJS#18]
When I created the UI mockup of the app the notification was exactly at the bottom of the page related to the browser window.

Once I converted the mockup to proper app using AngularJS all the notifications are pushed in the very bottom of the body, so I should scroll down to see them...

Problem spotted using Chrome Version 39.0.2171.99.
On Firefox version 35.0 it work as expected.

Any idea how to fix this issue?

**Comment by MohammadYounes** [comment]
It's hard to tell without having a code sample! The notifier has a fixed position, so it should not require scrolling ...  can you provide a sample (You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started.)

**Comment by Torone** [comment]
I can not reproduce it on codepen, probably there is an error in my css, I will double check it.
Thanks.
