### ISSUE TITLE
Styling varies for different html pages

### ISSUE THREAD

**Issue by Kickbuttowaski** [MohammadYounes/AlertifyJS#180]
The alertify.alaert box that I create is coded with the stylings of my wish
This styling varies from page to page

say .. Before log in, I get the alert box with the styles that I have written whereas after logging in  to the page the styling of the alert boxes changes whereas the content remains the same !

**Comment by MohammadYounes** [comment]
Most probably you have global styles affecting AlertifyJS elements, try to check the included styles in the before login and after login pages to find out what styles are getting applied.
