### ISSUE TITLE
Can't drag the alert dialog box

### ISSUE THREAD

**Issue by JimWang1995** [MohammadYounes/AlertifyJS#182]
async alert(...args) {
    
    // do something to deal with string
    let strCount = args.filter(l => typeof l == 'string').length;
    if (strCount == 1)
      args = ["alert.message"].concat(args);
    args[0] = await this.getTranslate(args[0]); // get a string
    args[1] = await this.getTranslate(args[1]); // get a string
    args[2] = args[2] || true;

    alertify.alert().setting('modal', false);  //  set  modal
    alertify.alert(...args);
  }

Some time it works , sonme time can't drag the alert dialog box.
What went wrong?

**Comment by JimWang1995** [comment]
alertify: any = window["alertify"];

// onInit()
    this.alertify.alert().set({ 'modal': false, movable: true });
    let v = "some message"
    this.alertify.alert(v)


If use "Ctrl+F5" to refresh chrome , it can't be moved.
then use "F5" to refresh chrome , it can  be moved.

**Comment by MohammadYounes** [comment]
Can you share a sample project to troubleshoot ?

**Comment by JimWang1995** [comment]
https://github.com/JimWang1995/questiondemo

**Comment by MohammadYounes** [comment]
@JimWang1995 I got very busy lately and wasn't able to follow up on this. The repo you shared seems to be deleted. Is this issue resolved ?

**Comment by JimWang1995** [comment]
I didn't change the code. Suddenly it was good. The reason was unknown.

**Comment by MohammadYounes** [comment]
Ok then, closing the issue.

Thanks!
