### ISSUE TITLE
Nested confirms

### ISSUE THREAD

**Issue by snout-o** [MohammadYounes/AlertifyJS#184]
Hi

Apologies if this has been asked before but I'm wondering how one would go about nesting confirms?

e.g.
`alertify.confirm('Confirm Message', function(){ alertify.confirm('Second confirm message', function(){console.log('done');}) });`

I've tried setting a flag to true in the first callback and then setting my next call to confirm in the "onclose" event, like below, but that also doesn't work. In both cases the second call to confirm fails to show anything.

`var flag=false;
alertify.confirm('Confirm Message', function(){ flag=true; }).set({onshow:null, onclose:function(){  if(flag){ alertify.confirm('Second confirm message', function(){console.log('done');})}}); `

**Comment by snout-o** [comment]
Alright using setTimeout to create an async callback appears to work:

`alertify.confirm('Confirm Message', function(){ 
   setTimeout(function(){
      alertify.confirm('Second confirm message', function(){
         console.log('done');
      });
   },0); 
});`

Would like to hear if there's a better way to accomplish this, however.

**Comment by MohammadYounes** [comment]
Hi @snout-o,

With current implementation a `setTimeout` is the way to go, Since `confirm` is a singleton and the actual closing occurs after transition ends. 

Thanks!
