### ISSUE TITLE
if set Content,how to get value?

### ISSUE THREAD

**Issue by JimWang1995** [MohammadYounes/AlertifyJS#185]
alertify.prompt()    
.setContent('<textarea> Hello World! </textarea>')
.set('onok', function (closeEvent){ 
      alertify.success('Ok');
 } )
.show();

how to get the words from textarea?

**Comment by MohammadYounes** [comment]
@JimWang1995 You need to query the element to read its value

```js
function fn() {
  alertify.prompt()
    .setContent('<textarea> Hello World! </textarea>')
    .set('onok', function(closeEvent) {
      alertify.success(this.elements.content.querySelector('textarea').value);
    }).show();
}
```

See example http://jsfiddle.net/dLmodhe0/
