### ISSUE TITLE
Displaying HTML Unicode symbols in Alertify messages

### ISSUE THREAD

**Issue by Verkoj** [MohammadYounes/AlertifyJS#187]
How can HTML Unicode symbols begining with & be displayed in messages (like & spades; or & #9824;  both should show ♠)?
(I added here space after the &, otherwise the symbol is displayed in browser.) 
When I tried it in Alertify,  & #9824;  was displayed, and not the symbol ♠ itself.

**Comment by MohammadYounes** [comment]
@Verkoj I see no problem with displaying HTML entities, See http://jsfiddle.net/3vpfpp5p/.
