### ISSUE TITLE
alertify visible on load/startup

### ISSUE THREAD

**Issue by seltix5** [MohammadYounes/AlertifyJS#190]
Hello,
Sometimes, for some reason (probably because the JS loads before the CSS or just because browser rendering), for a second the empty alertify div with ajs-dimmer and ajs-modal is visible until the class "ajs-hidden" make it invisible as normal.
Is there a way to prevent this situation?
Thank!

**Comment by MohammadYounes** [comment]
@seltix5  You can ensure that `ajs-hidden` is present by including it inline in the page head

```html
<style>
.alertify.ajs-hidden .ajs-dimmer, .alertify.ajs-hidden .ajs-modal {visibility:hidden;opacity:0;}
</style>
```

Is it possible to provide an online example to see what's really happening ?

**Comment by seltix5** [comment]
Hello,
That solved the problem, thanks!
