### ISSUE TITLE
alertify confirm hide on top of mobile screen

### ISSUE THREAD

**Issue by shw2ypro** [MohammadYounes/AlertifyJS#192]
i'm using alertify with phonegap

i have astrange case in some mobile

alertify confirm box is hide on top

this is the normal case https://suar.me/G1EL6

this is a strange case https://suar.me/yqEZn

Please Help

Thanks In Advance
![jkhkjhkhk](https://user-images.githubusercontent.com/42306106/43996830-f0675de2-9dcb-11e8-8e6a-71763bb3fa41.jpeg)
![whatsapp image 2018-08-12 at 12 30 10 am](https://user-images.githubusercontent.com/42306106/43996831-f09a0efe-9dcb-11e8-8e14-b2bc52813ad8.jpeg)

**Comment by MohammadYounes** [comment]
@shw2ypro  It's hard to tell, may be another style is interfering with the dialog ?

**Comment by MohammadYounes** [comment]
Closing due to lack of a test case.
