### ISSUE TITLE
alertify.error() - custom width

### ISSUE THREAD

**Issue by sanju4ever** [MohammadYounes/AlertifyJS#195]
It does not seem "alertify.error()" dialogbox supports changing its width.
I tried below:
alertify.error('Error occurred.').set('resizable',true).resizeTo('50%',100);

Any thoughts? I just want to change only the "width".
"height" could just be "auto".

**Comment by MohammadYounes** [comment]
@sanju4ever  Notification messages are different from dialogs, They do not support setting width. However, you can use CSS to customize them as you see fit. 

See the example in this [comment](https://github.com/MohammadYounes/AlertifyJS/issues/191#issuecomment-409367034), which gives the notification message a full width.

Thanks!

**Comment by OnbitShashan** [comment]
Here a fix for if anyone using out there 
.alertify-notifier .ajs-message {
  width: max-content !important;
}

which will give you dynamic notfiers according to your title
