### ISSUE TITLE
Extra empty white notification on startup

### ISSUE THREAD

**Issue by vlad1777d** [MohammadYounes/AlertifyJS#197]
Hello.

If I add .css files from this library to empty page, it'll display empty white notification when page is loaded.
Even it's not required to add .js file to page.

Example: https://youtu.be/wzO5EpREMbg

Screenshot: 
![screenshot from 2018-09-15 13-19-26](https://user-images.githubusercontent.com/12682937/45586826-945e8e80-b905-11e8-8a14-9b2b1fed7804.png)

Probably the problem is somewhere in `alertify/css/alertify.css`, only it's removing affects on notification displaying.

Is present on Firefox 61, 62.
OS: Linux Mint x64 19 Cinnamon

Tried 1.11 version, 1.10, 1.5 - result is the same.

Couldn't reproduce on latest Chromium.

Can someone help me with it.
I think it's not the same as https://github.com/MohammadYounes/AlertifyJS/issues/190 , because that solution didn't worked for me.
Notification has different classes (see screenshot).

Thank you.

**Comment by MohammadYounes** [comment]
Is it possible to create a test case?  You can fork this [codepen](http://codepen.io/anon/pen/raohK) to get started.

**Comment by vlad1777d** [comment]
@MohammadYounes ,
tried to reproduce it on codepen, but unsuccessfully.

But it reproduced in one local .html page.
I compressed to .zip it.
It has one .html file and alertify.js library.
![screenshot from 2018-09-20 00-56-51](https://user-images.githubusercontent.com/12682937/45784020-1b966400-bc70-11e8-99ad-626e4e556e40.png)
[test_cases.zip](https://github.com/MohammadYounes/AlertifyJS/files/2398848/test_cases.zip)

**Comment by vlad1777d** [comment]
@MohammadYounes , seems, you used Chrome or Chromium to reproduce it.
I could only reproduce it with latest version of Firefox (62).

If you want, I can show you it with teamviewer, but we'd need to choose time when I'll be at home (it's on my home machine).

**Comment by MohammadYounes** [comment]
@vlad1777d Sure, Would tomorrow work for you ?

**Comment by vlad1777d** [comment]
@MohammadYounes , sorry, read very late this.
I can do this in Sunday (today) after 12.00 GMT + 2.

Do you have Telegram, or FB ?

**Comment by MohammadYounes** [comment]
@vlad1777d If you are available next Friday/Saturday afternoon, just mention the time and I'll confirm availability.

**Comment by vlad1777d** [comment]
@MohammadYounes , Yes, I'll be able on Saturday almost any time.
I thought that we could contact through any chat or IRC, maybe, or Facebook, or something like this.

Because Github doesn't send notifications for me.

**Comment by MohammadYounes** [comment]
@vlad1777d  What about https://gitter.im/MohammadYounes/AlertifyJS ?

**Comment by vlad1777d** [comment]
@MohammadYounes , thanks, joined it.
I'll try not to forget about this =)

**Comment by vlad1777d** [comment]
Thanks @MohammadYounes , he found that it's due to extension.
Simple Video Downloader added transparent notifications, which were styled by alertify.

https://addons.mozilla.org/en-US/firefox/addon/simple_video_downloader/
(version 2.10 was installed)
