### ISSUE TITLE
Bootstrap theme ignored when using dialog factory

### ISSUE THREAD

**Issue by dpage** [MohammadYounes/AlertifyJS#20]
I'm successfully using the Bootstrap them with alerts and prompts etc, however it seems that dialogs continue to use the default theme. I'm using the following settings, and have included the correct stylesheets:
```
alertify.defaults.transition = "zoom";
alertify.defaults.theme.ok = "btn btn-primary";
alertify.defaults.theme.cancel = "btn btn-danger";
alertify.defaults.theme.input = "form-control";
```
![screen shot 2015-01-28 at 13 52 37](https://cloud.githubusercontent.com/assets/316438/5938724/9776ceaa-a6f5-11e4-84d2-7422a98dcec1.png)

Thanks for any help you can give.

**Comment by MohammadYounes** [comment]
Actually! it's not ignored, seems you didn't set the `className` in your buttons definition. See [buttons definition](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/confirm.js#L88-L99) in the built-in confirm dialog.

**Comment by dpage** [comment]
Ah, of course. Thank you very much for the prompt reply - it works as expected now.
