### ISSUE TITLE
Different Theme for different dialog

### ISSUE THREAD

**Issue by JansenLam** [MohammadYounes/AlertifyJS#200]
Hi,

I wish to create two separate confirm dialogs with different color of the OK button. I tried the followings

           $('#button1').on('click', function (e) {
                alertify.defaults.theme.ok = "btn btn-primary";
                alertify.defaults.theme.cancel = "btn btn-default";
                alertify.defaults.theme.input = "form-control";
                alertify.confirm().setting({
                    title: "title",
                    message: "primary"
                }).show();                
            });
            $('#button2').on('click', function (e) {
                alertify.defaults.theme.ok = "btn btn-danger";
                alertify.defaults.theme.cancel = "btn btn-default";
                alertify.defaults.theme.input = "form-control";
                alertify.confirm().setting({
                    title: "title",
                    message: "danger"
                }).show();                
            });

but it is not working.

It seems that the theme is initialize during the first click. And the theme of the second dialog is not able to change.

Am I missing something?

Any help is welcome.

Regards,
Jansen Lam

**Comment by MohammadYounes** [comment]
@JansenLam Global settings are read once upon creating the dialog, changing them like this wont have any effect. 

However, you can [`destroy`](https://alertifyjs.com/confirm/destroy.html) the dialog, change the defaults then create a new one.

```js
alertify.confirm().destroy();
alertify.defaults.theme.ok = ...
```

Or you can apply a custom class on [`show`](https://alertifyjs.com/confirm/show.html), as in #144 

Thanks.

**Comment by JansenLam** [comment]
Good! Thanks.

在 2018年10月29日週一 下午6:06，Mohammad Younes <notifications@github.com 寫道：
