### ISSUE TITLE
resizable dialog style becomes empty when resize browser window

### ISSUE THREAD

**Issue by xxjapp** [MohammadYounes/AlertifyJS#202]
For example, dialog with the following style

```html
<div class="ajs-dialog" tabindex="0" style="height: 564px; min-height: 108px; width: 888px; min-width: 548px; max-width: none;">
```

When browser window resizes, will become to the following:

```html
<div class="ajs-dialog" tabindex="0" style="">
```

**Comment by xxjapp** [comment]
[https://alertifyjs.com/alert/autoReset.html](https://alertifyjs.com/alert/autoReset.html)
seems to solve the problem

**Comment by MohammadYounes** [comment]
@xxjapp  Yes, and you can use [defaults](https://alertifyjs.com/guide.html#defaults) to disable it globally.
