### ISSUE TITLE
Flash of empty alert if defered CSS not yet loaded (avoid FOUC)

### ISSUE THREAD

**Issue by utilmind** [MohammadYounes/AlertifyJS#205]
Hello! Situation is following... I am defering load of CSS with rel="preload" and changing it to rel="styleshit" with when CSS loaded. I know that rel="preload" not supported by some browsers, particularly it's not available at FireFox.

But in case if Alertify's JavaScript asynchronously loaded before CSS, an empty alert box appears for a moment before loading of CSS (before implementing "classes.hidden" style, named 'ajs-hidden').

I suggest to hide the root DIV element of Alertify box with inline styling, to avoid flash of unstyled content (FOUC):

```
elements.root.className = classes.base + ' ' + classes.hidden + ' ';
elements.root.style.display = 'none'; // AK - hide upon first initialization to avoid FOUC.
```

```
// show dialog
this.elements.root.style.display = ''; // AK - unhide
removeClass(this.elements.root, classes.hidden);
```

**Comment by MohammadYounes** [comment]
Hello, This will be fixed in next update. 

For the time being, adding the following to page head would prevent FOUC.
```html
<style>
.alertify.ajs-hidden .ajs-dimmer, .alertify.ajs-hidden .ajs-modal {visibility:hidden;opacity:0;}
</style>
```
