### ISSUE TITLE
New instances use the functions of the old instance

### ISSUE THREAD

**Issue by anotherCoward** [MohammadYounes/AlertifyJS#208]
Heyho,

I'm not sure if this is by design or a bug.
```js
alertify.alert('title', 'some stuff', function onclose() {
  // this.destroy() should be executed by default after the onclose function is called.
  // if i would want to use the same stuff again, i would apply it here...
  setTimeout(function() {
     // without AlertifyInstance.destroy() it ends in an endless loop.
     alertify.alert('other title','some more stuff');
   },1000);
  // uncomment for testing
  // this.destroy();
});
```
Using this, ends up in an endless loop and recalls the timeout on every close on the second note. I am not sure, if this is by design or not, but this reads for me as a new instance is created after the first note was closed.

Greetings

**Comment by MohammadYounes** [comment]
Yes, This is by design.  All of the built-in dialogs are singletons, they will maintain their options unless destroyed.  

Either clear the callbacks by setting them again to `null` or `undefined` or use  [`.destroy()`](http://alertifyjs.com/alert/destroy) method to reset all options.

Thanks!

> Dup: #177 #154
