### ISSUE TITLE
Default Button Labels

### ISSUE THREAD

**Issue by anotherCoward** [MohammadYounes/AlertifyJS#209]
Hiho,

there should be at least 4 default labels depending on the action itself.

The confirm dialog might need something like yes/no or accept/decline, while the alert/prompt dialogs needs ok/cancel.

I know its possible to change those settings with set/settings. But for the most cases i just want to use language related ok/cancel/yes/no buttons based on the default dialogs.

I'm also aware of the fact that it might break existing scripts, working with the actual two labels, but it would be a nice addition in future releases.

Greetings

**Comment by MohammadYounes** [comment]
I'll keep this in mind for the next major version.

Thanks!

**Comment by anotherCoward** [comment]
Hiho again,

there would be another solution without breaking the current behavior, just check if ``settings.accept/decline`` is defined. if so, use those instead of ``settings.ok`` and ``settings.cancel``. (even tho you could split it up in ``settings.alert-ok``, ``settings.confirm-ok`` and so on) 

This wouldn't break any existing scripts and would add support for these options as suggested.

Greetings

**Comment by MohammadYounes** [comment]
@anotherCoward How are you using this ? Did you implement an external wrapper to set the labels per call ? Can you provide a code sample for using such feature ?

**Comment by anotherCoward** [comment]
A snipped based on your code or just an example?
(on confirm dialog)
```js
if (settings.accept) {
  /* use this for the label */
} else {
  /* default behavior use settings.ok */
}
```
This would give them another priority if they are defined, but stays the same if they are not present. 

This would allow something like mentiond in my suggestion without breaking existing scripts.
For example:
```js
// as before, fallback/default values
alertify.defaults.glossary.ok = lang.getText('ok');
alertify.defaults.glossary.cancel = lang.getText('cancel'); 
// should be preferred over ok on alertify.confirm()
alertify.defaults.glossary.accept = lang.getText('accept'); 
// should be preferred over cancel on alertify.confirm()
alertify.defaults.glossary.decline = lang.getText('decline'); 
```

Line 90 in confirm.js
```js
                            text: alertify.defaults.glossary.ok,
```
Should just be changed to
```js
text: typeof alertify.defaults.glossary.accept != 'undefined' && alertify.defaults.glossary.accept !== null ?
  alertify.defaults.glossary.accept :
  alertify.defaults.glossary.ok,
```
Greetings :)

**Comment by MohammadYounes** [comment]
@anotherCoward I just needed a usage example :)
