### ISSUE TITLE
modal dialogs without close on click

### ISSUE THREAD

**Issue by dantman** [MohammadYounes/AlertifyJS#21]
One missing option appears to be the ability to have a modal dialog in which clicking on the dimmer doesn't trigger the close action.

**Comment by MohammadYounes** [comment]
Have you tried [`closable`](http://alertifyjs.com/alert.html#closable) option?

**Comment by dantman** [comment]
Closable affects the whole closabilty of the dialog, including the x close icon.

I do want the dialog to be closable. I just don't want it to automatically close when someone accidentally clicks outside the dialog for certain big and important dialogs.

**Comment by MohammadYounes** [comment]
So you want to keep the close command but prevent the dimmer from triggering close event. I can add a new global default `alertify.dimmerTriggerClose: true` to maintain backward compatibility.

Does this work for you ?

**Comment by MohammadYounes** [comment]
Or per instance, by adding a new option `closableByDimmer: true` ?

**Comment by dantman** [comment]
Yeah, that's the idea.

And yes, per instance. This is only for certain types of dialogs.

```js
alertify.alert('Modal: false').set({modal: true, closableByDimmer: true});
```

**Comment by dantman** [comment]
I'll even give an example.

One of the dialogs I'm planning to add opens when a user who is logged in with a username and password does an action that requires a Facebook login. It explains that to them and lets them connect their account to Facebook before continuing.

It wouldn't make sense for an accidental tap on the dimmer to close the dialog, stop them from reading it and connecting their account, and aborting what they were doing.

But it would make sense for them to click on an x and cancel out from the dialog explicitly aborting it.

**Comment by MohammadYounes** [comment]
I see, I'll add this later tonight.
