### ISSUE TITLE
SCRIPT5045: Assignment to read-only properties is not allowed in strict mode IE11

### ISSUE THREAD

**Issue by slolo2000** [MohammadYounes/AlertifyJS#210]
Hello,

Since the version 1.11.3 of AlertifyJS, I got the following error message with Internet Explorer 11 and jQuery v3.4.1:

> SCRIPT5045: Assignment to read-only properties is not allowed in strict mode

I do not have the error with the version 1.11.2

I have done a small example under JSFiddle: http://jsfiddle.net/g2o52zq7/

If you click on links "alert", "confirm" or "prompt" with developper console opened you will see the following error message:

> SCRIPT5045: Assignment to read-only properties is not allowed in strict mode
alertify.js (514,17)

If I go to the following line, it seems to be this piece of code which cause the error message:
```    
    //prevent FOUC in case of async styles loading.
    elements.root.style = 'display:none';
```
Are you able to reproduce it?

Thanks in advance for your help and have a nice day.

**Comment by MohammadYounes** [comment]
Thanks for reporting this, It should be: `elements.root.style.cssText = 'display:none';`

 Will fix soon.
