### ISSUE TITLE
Notifications not working in Chrom

### ISSUE THREAD

**Issue by w2kzzz** [MohammadYounes/AlertifyJS#211]
hi,

it seems that the notifications are no longer working in Chrome, i'm clicking on the examples on your web and they don't display, however they seems to be working on safari and firefox.

**Comment by MohammadYounes** [comment]
I checked in Chrome and they seem to be working just fine!

**Comment by w2kzzz** [comment]
thanks a lot for the response, i'm checking the tools and i see the div being modified with the classes, but nothing in the screen, is there any particular version you're using? i already checked my version and the weird thing is that it was working before

**Comment by slolo2000** [comment]
Hello w2kzzz,

Have you tried to open the "Chrome Developer Tools Box" (Ctrl+Shiht+I) and see if there is an error into the console?

For me, it works very well with Chrome Version 75.0.3770.90 (x64) under Windows 10 (x64) build 1903.

**Comment by MohammadYounes** [comment]
@w2kzzz Your original post indicated this is a problem with the website [www.alertifyjs.com](https://www.alertifyjs.com), which I checked! 

If this is a different site, make sure alertifyjs CSS files are included in your page

```html
<!-- include the style -->
<link rel="stylesheet" href="path/to/alertify.min.css" />
<!-- include a theme -->
<link rel="stylesheet" href="path/to/themes/default.min.css" />
```

**Comment by MohammadYounes** [comment]
Closing due to lack of details.
