### ISSUE TITLE
Dialogs Factory change dialog div class

### ISSUE THREAD

**Issue by str1gh** [MohammadYounes/AlertifyJS#213]
Hi everyone,

I've created a custom alert via Dialogs Factory named "alertSuccess".
I would like to remove the default "**ajs-dialog**" css class and replace it with something like "**ajs-success**" for the "success" dialog.

I've tried with some things like that but it don't work...

```
build:function(){
   this.elements.dialog = "ajs-success";
},
```

Could somebody explain me how to do this (if it's possible) ?

Thank you !

**Comment by MohammadYounes** [comment]
To change the class name of the dialog element, you need to set it via `.className=...`

```js
build:function(){
   this.elements.dialog.className = "ajs-success";
},
```

**Comment by str1gh** [comment]
> 
> 
> To change the class name of the dialog element, you need to set it via `.className=...`
> 
> ```js
> build:function(){
>    this.elements.dialog.className = "ajs-success";
> },
> ```

@MohammadYounes Thank you !
