### ISSUE TITLE
How do I override keyuphandler(event) function?

### ISSUE THREAD

**Issue by mzabuawala** [MohammadYounes/AlertifyJS#214]
The issue is that I am using Select2 combobox on Alertify dialog, now whenever I try to select the select2 option using keyboard by pressing Enter key the dialog closes because the Enter key is bind to Ok button and and ESC key is bind to Cancel button, I installed AlertifyJS using npm/yarn and I want to override keyupHandler handler function without changing int the source file.
```

import alertify from 'alertify';

// How can I override the default keyupHandler function after importing it in my code?
```

I want to add validation that if event.target is Select2 and it is open then do not trigger the events which close the dialog.

**Comment by MohammadYounes** [comment]
You may combine events from both libraries to achieve this. First, listen to `open`/`close` events of select2, then use them to allow or deny closing the dialog.

```js
var isClosed = false
// wire select2 events
$('select').select2().on('select2:open', function(e){
  isClosed = false
}).on('select2:close', function(e){
  setTimeout(function(){
    isClosed = true
   },200)
});

// wire alertifyjs events
alertify.confirm('message', function(){
  return isClosed
})
```


see example https://codepen.io/anon/pen/QebxYQ
