### ISSUE TITLE
Custom dialog and events not firing

### ISSUE THREAD

**Issue by ray73864** [MohammadYounes/AlertifyJS#215]
I'm using the Dialogs Factory to create a custom dialog, grabbed the version from 'examples' since mine didn't seem to be working properly, but for some reason the events don't always fire.

```
alertify.myDialog || alertify.dialog('myDialog',function(){
          return {
            main:function(content){
              this.setContent(content);
            },
            setup:function(){
              return {
                focus:{
                  element:function(){
                    return this.elements.body.querySelector(this.get('selector'));
                  },
                  select:true
                },
                options:{
                  basic:true,
                  maximizable:false,
                  resizable:true,
                  padding:false
                }
              };
            },
            settings:{
              selector:undefined
            }
          };
        });
```

I then run my new dialog as
```
alertify.vealeDialog("My custom dialog").set({
      onShow: function() { alert("onShow"); },
      onFocus: function() { alert ("onFocus"); },
      onClosing: function() { alert("onClosing"); },
      onClose: function() { alert("onClose"); }
    }).resizeTo(1600,200);
```

If I refresh the page, neither the 'onShow' or 'onFocus' events occur, however if I close the dialog and then re-open it again, the whole thing works fine.

Also, I have things I need to do inside of the dialog (such as attach event listeners for dynamically created things inside of it), how would I get the dialog object itself?

I thought using 'this', but that returns the alertify object, and I couldn't see a way to get it.

**Comment by MohammadYounes** [comment]
event names are all small letter, try this:

```
alertify.myDialog ("My custom dialog").set({
      onshow: function() { alert("onShow"); },
      onfocus: function() { alert ("onFocus"); },
      onclosing: function() { alert("onClosing"); },
      onclose: function() { alert("onClose"); }
    }).resizeTo(1600,200);
```

**Comment by ray73864** [comment]
Changing the events to be all lowercase didn't make any difference. if I set a breakpoint on the chrome devtools for the 'alert' inside the onshow(), it doesn't trigger when first opening the dialog, but does for subsequent openings.

**Comment by MohammadYounes** [comment]
@ray73864 This is because `onshow` was set after the dialog was shown. In case you want it to fire the first time, you should set it first then show the dialog.
```js
alertify.myDialog().set({
      onshow: function() { alert("onShow"); },
      onfocus: function() { alert ("onFocus"); },
      onclosing: function() { alert("onClosing"); },
      onclose: function() { alert("onClose"); }
    }).show().resizeTo(1600,200);
```
