### ISSUE TITLE
Feature request :) noPropagateClicks

### ISSUE THREAD

**Issue by utilmind** [MohammadYounes/AlertifyJS#216]
Hello! I have added a new option in my fork, noPropagateClicks. This option prevent passing the clicks events to other event listeners, when the alert is displayed.

This has solved my problem, which was following...

My customer's website has some legacy code for the "side windows". Those windows listening for the click events of &lt;body&gt; and hiding itself on each click outside the window.
I must prevent them from hiding when the alert is displayed. However, unfortunately, I can't use isOpen() method to test whether the alert box is displayed. After any click on the alert's OK button or dimmer, isOpen() will return false. The side windows catching that click, recognizing it as "outside" click and hiding itself (which is wrong).

So it looks like the only solution to not pass the clicks to other listeners outside of an alert -- is to prevent their propagation.

And It would be really cool if you can add noPropagateClicks or similar option to the canonical version of AlertifyJS.

Thank you!

**Comment by utilmind** [comment]
Oh, I forgot to add link to my fork. Here is it: https://github.com/utilmind/AlertifyJS/commit/dfd66b236656a4a68e8d299033e324ede83538ed#diff-c00d4b32a9368e7ede27747e63502911

**Comment by utilmind** [comment]
Please disregard my suggestion above. Unfortunately it prevents clicking the links in alerts. I'm working on better solution.

**Comment by utilmind** [comment]
Here is final fork, which displaying what could be updated:
https://github.com/utilmind/AlertifyJS/commit/4ad0d4600610b00ec04cd675290dc027dc29b163#diff-c00d4b32a9368e7ede27747e63502911

**Comment by MohammadYounes** [comment]
Thanks for the details. However, I believe adding the below line after creating the [root element](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/dialog/intro.js#L178) is enough?

```js
elements.root.onclick = function(e){e.stopPropagation()}
```

**Comment by utilmind** [comment]
No, unfortunately this will not work. Because the legacy code also listens for all clicks of the root element. It's also "closable by dimmer".

Let's imagine that page uses 2 libraries for modal windows. Both libraries can display popup windows, "closable by dimmer". But I would like to give an AlertifyJS higher priority for the "dimmer area", and allow Alertify alerts over another non-alertify modal windows.

**Comment by MohammadYounes** [comment]
The dimmer is placed inside the root element and it's always [added](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/dialog/intro.js#L289) at the end of the document (which ensures being on top of elements having the same z-index). 

> Because the legacy code also listens for all clicks of the root element. 

How would the legacy code listen to the click events of AlertifyJS root element ? Can you provide an online sample ?

**Comment by utilmind** [comment]
There is following code which uses jQuery:

```
$("body").on("click", function(a) { // click anywhere
         $(side_window).hide(); // hide window on any click outside of it
 });

```

**Comment by utilmind** [comment]
Yes, I was wrong when I called it "dimmer". It just listens to all clicks over document.body. I see that Alertify really adding another separate elements as "dimmer". However any "propagated" clicks closing the side windows.

**Comment by MohammadYounes** [comment]
This won’t catch the clicks on the Dialog or the Dimmer if AlertifyJS root element stops event propagation.


Try adding this after [creating](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/dialog/intro.js#L178) the root element.

```js
elements.root.onclick = function(e){e.stopPropagation()}
```

**Comment by MohammadYounes** [comment]
@utilmind no worries!

**Comment by utilmind** [comment]
Hello! I have added suggested code after creating of elements.root into https://palmbeachcuisine.com/js/alertify.test.js:

```
                elements.root = document.createElement('div');
                if (instance.get('noPropagateClicks') === true)
                  elements.root.onclick = function(e){e.stopPropagation()}

```

However it doesn't works as expected. It still propagate event on OK button, or on Enter keypress.

Here is the page which reproduces the problem:
https://palmbeachcuisine.com/rs-test.html#BistroJupiter
The side window contains "Redeem" field. Just enter some invalid email address, like "test@test" to see the Alertify box. Side window really keeping opened on clicks inside the Alertify box, but unfortunately closes after clicking OK.

Here is how it should work:
https://palmbeachcuisine.com/restaurant-specials.html#BistroJupiter
To reproduce -- also type any invalid email in Redeem box, like "test@test" to see an Alertify. This Alertify with my suggested noPropagateClicks option works well.

**Comment by MohammadYounes** [comment]
@utilmind When debugging through your updated version `instance.get('noPropagateClicks')` returns `undefined` as the default hasn't been set yet.

**Comment by utilmind** [comment]
Yes, really :) But I still prefer to have configurable noPropagateClicks. Who knows, maybe I will want to hook all clicks in one of my future project.

In any case the following code works well at https://palmbeachcuisine.com/rs-test.html#BistroJupiter:
```
                elements.root = document.createElement('div');
                if (defaults.noPropagateClicks === true)
                  elements.root.onclick = function(e){e.stopPropagation()}

```

**Comment by MohammadYounes** [comment]
v1.12.0 introduces two new [global hooks](https://alertifyjs.com/guide.html#defaults) (`preinit` and `postinit`), you can use them to wire your own click event, stopping propagation at root element.

```js
alertify.defaults.hooks.postinit = function(instance){
  instance.elements.root.onclick = function(e){e.stopPropagation()}
}
```
