### ISSUE TITLE
Feature request: 3 dialog buttons (Yes / No / Cancel)

### ISSUE THREAD

**Issue by slolo2000** [MohammadYounes/AlertifyJS#218]
Hello,

Would it be possible to have a new type of dialog with 3 buttons (Yes / No / Cancel) by default.

I know it can be done with Dialogs Factory but I think it can be nice to have this dialog box in a new default component.

If not, is it possible to add a new example on web site with the implementation of this new type of dialog box.
I am sure it will be useful for a lot of AlertifyJS users.

**Comment by utilmind** [comment]
Some time ago I wanted Cancel button too. But decided to make my dialog boxes more straightforward with only Yes or No question (and its custom variations). But I still getting kind of Cancel action. Any ESC keypress or clock of Close (X) button considered as cancel.

**Comment by MohammadYounes** [comment]
@slolo2000 The builtin ones were created to mimic the default browser dialogs, In case we added such dialog, what will we name it ?

@utilmind ESC/X only trigger the action of the first button having `invokeOnClose` set to `true`.
see [dialog factory](https://alertifyjs.com/factory.html#factory).

**Comment by slolo2000** [comment]
@MohammadYounes You are right about the original aim of alertifyjs to mimic default browser dialogs box. Now you have to decide if your plugin needs to do more than default browser or not. I think it would be a nice feature, useful for many situations in coding.

For the name, it could be something like alertify.question or alertify.choice

**Comment by tmbsis** [comment]
I support the idea of the "yes/no/cancel" set of buttons

**Comment by MohammadYounes** [comment]
@slolo2000 Would an option such as `invokeOnCloseOff` eliminate the need for 3 buttons ?

**Comment by slolo2000** [comment]
@MohammadYounes
It is a nice Idea yes ans it could simulate the need for 3 buttons.
Like that, the plugin stays in its original needs of mimic defaults dialog box.

**Comment by MohammadYounes** [comment]
Closing this in favor of #219

**Comment by MohammadYounes** [comment]
Available in v1.12.0  - https://alertifyjs.com/confirm/invokeOnCloseOff
