### ISSUE TITLE
Cancel and Close button behaviors are same in Alertify.Confirm() 

### ISSUE THREAD

**Issue by RockNrola** [MohammadYounes/AlertifyJS#219]
How to disable InvokeOnClose property of the cancel button in Confirm popup? I read all the documents and found that we have to create a customized confirm popup using dialogs factory. That doesn't make any sense.

**Comment by slolo2000** [comment]
Hello,

Your request is a bit like mine (see https://github.com/MohammadYounes/AlertifyJS/issues/218)
In fact, you want to have the possibility to confirm with Yes or No or Cancel.

I hope this dialog box will be added in future release.

**Comment by MohammadYounes** [comment]
@RockNrola I'll consider it in the next update.

**Comment by MohammadYounes** [comment]
Closed in 98133853e480b523160fcb8049c3f08b58c4ce91, see https://alertifyjs.com/confirm/invokeOnCloseOff
