### ISSUE TITLE
Feature request: respect "prefers-reduced-motion" @media rule

### ISSUE THREAD

**Issue by utilmind** [MohammadYounes/AlertifyJS#224]
Hello! It would be excellent if the next version of Alertify will have an option to respect the CSS @media rule:

```
@media (prefers-reduced-motion:reduce) {
 disable all transitions/animations inside
}
```

Some users prefers to see as less animations as possible in the performance settings of their devices. The new option of Alertify should disable all animation for these users, respecting the performance preferences in their OS.

**Comment by utilmind** [comment]
Hello :) I feel awkward, but want to ask to partially return back the transitions. :)

Some webmaster may want to deliberately ignore "prefers-reduced-motion" and display the animation in any case.

So the best will be replace "transitionOff" option to "showTransition" with 3 options: true (always show transitions), false (never show transition) and "auto" (default option, browser respects "prefers-reduced-motion").

Thank you!

**Comment by MohammadYounes** [comment]
@utilmind I had a hard time thinking about this yesterday. However, I came to the conclusion that if someone doesn't want to to support `prefers-reduced-motion`, then removing the media query  is the way to go :)

**Comment by utilmind** [comment]
In most cases I would like to respect user settings, except and error alert, where I would like to display particular importance of message with pulse animation, even if user disabled most in-windows animation.

So I still would prefer showTransition property with 3 options: true, false and "auto" (default).

Please check out the JS and CSS in my fork:
JS: https://github.com/utilmind/AlertifyJS/commit/01794340249e2a478865943205a619e3731570e1#diff-c00d4b32a9368e7ede27747e63502911

CSS: https://github.com/utilmind/AlertifyJS/commit/505a5d539382a3e5e0996948149e151ca97d5d28#diff-14f6eaf32ac8b1f0af5e880fa1f0f793

I hope you can make this standard.

Also I noticed that ESC button and click on dimmer does not works even if animation turned off. I think that it's somehow related to ajs-in / ajs-out styles. They probably should not be added if animation turned off, so alert window can react the keyboard and mouse events immediately once it displayed without need to wait while invisible animation ends.

**Comment by MohammadYounes** [comment]
I don't want to introduce any breaking changes, this will be revised in v2
