### ISSUE TITLE
Can't hide footer and show header in dialog

### ISSUE THREAD

**Issue by Syltty** [MohammadYounes/AlertifyJS#227]
Hi,

I'd like to show the header without showing the footer. It seems that it's not possible but I may (hope) be wrong!

options: {
 frameless: true // disable header AND footer
}

Note: The dialog contains an iframe.

**Comment by MohammadYounes** [comment]
Unfortunately, such option is not available in current version. However, footer space is not reserved, so adding a top margin to your iframe will make it look like there is a header.

**Comment by Syltty** [comment]
@MohammadYounes Hi, I need to identify dialogs with iframe on which I apply custom styling. Is there a way to inject id for example? thank you.
