### ISSUE TITLE
Feature request: random animation

### ISSUE THREAD

**Issue by utilmind** [MohammadYounes/AlertifyJS#229]
It would be cool, if `transition` property could support not single animation effect, but array of possible effects. And random effect can be chosen from provided array with some code like following:

`currentAnimation = Array.isArray(animationName) ? animationName[Math.floor(Math.random() * animationName.length)] : animationName;
`

And correct class name for animation effect (random effect) can be dynamically added right before the animation and removed together with ajs-in/ajs-out.

**Comment by MohammadYounes** [comment]
I don't think this fits as a standard feature. However, you can easily implement this using [global hooks](https://alertifyjs.com/guide.html#defaults).
