### ISSUE TITLE
Missing overflow: hidden in ajs-message

### ISSUE THREAD

**Issue by utilmind** [MohammadYounes/AlertifyJS#230]
Hello! ajs-message missing rule overflow: hidden. Otherwise long strings getting beyond the bounds of the notification div.

![Untitled](https://user-images.githubusercontent.com/5224442/70891118-99046d80-1fb4-11ea-85cd-bbd5cd7a41ac.png)

**Comment by MohammadYounes** [comment]
This is all controllable via CSS, I left it for the developer on a case by case basis (See https://github.com/MohammadYounes/AlertifyJS/issues/191#issuecomment-409367034)
