### ISSUE TITLE
Default Notifications not working in firefox while using uBlock Origin in Alertify website

### ISSUE THREAD

**Issue by abuassar** [MohammadYounes/AlertifyJS#232]
thanks for your hard work,

I noticed that **Default Notifications** examples in https://alertifyjs.com/ homepage
don't show in firefox if I enabled uBlock Origin
while It is working correctly if I disabled it.

**Comment by MohammadYounes** [comment]
This is related to #217. Seems it's filtered out based on class name see [here](https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L80) and [here](https://easylist-downloads.adblockplus.org/easylist-cookie.txt).

The solution is to rename [notifier class names](https://alertifyjs.com/guide.html#defaults).

Thanks.
