### ISSUE TITLE
Alert is shown out of viewport

### ISSUE THREAD

**Issue by rualark** [MohammadYounes/AlertifyJS#234]
![image](https://user-images.githubusercontent.com/15198808/73213556-70e65d80-4161-11ea-80ec-2c62f507937d.png)

https://artinfuser.com/harmony

I saw this only once in safari on iphone. What is interesting, scrolling down moves alert into correct position. It seems to happen when there are two alerts at the same time and also there is some interaction with user. This is how it should look like:

![image](https://user-images.githubusercontent.com/15198808/73213781-e05c4d00-4161-11ea-94db-73fa54ddb3fe.png)

**Comment by MohammadYounes** [comment]
@rualark I wasn't able to reproduce this on iPhone 6 

![image](https://user-images.githubusercontent.com/4712046/73332820-5a372800-4281-11ea-88ec-6f599cb677a1.png)

Is there a specific steps I should follow ?

**Comment by rualark** [comment]
As you can see, my zoom icons also fall out of the page. This seems to be a safari bug.
So far I couldn't reproduce, but I'll try

**Comment by MohammadYounes** [comment]
Closing this, feel free to reopen in case you were able to reproduce.
