### ISSUE TITLE
Concatenate prompt

### ISSUE THREAD

**Issue by kapi2454** [MohammadYounes/AlertifyJS#238]
Hi, thank for the great work.
I like to do a tutorial. FIrst a promp askme for a name, late a email etc
This not work :(
Thank you!!!

**Comment by MohammadYounes** [comment]
Hi, see this [answer](https://stackoverflow.com/questions/28278829/alertify-dialog-disappeared-before-confirming/28280448#28280448).

**Comment by MohammadYounes** [comment]
Closing this as resolved.
