### ISSUE TITLE
Confirm close triggers "Ok" being pressed

### ISSUE THREAD

**Issue by NodexTech** [MohammadYounes/AlertifyJS#24]
When clicking the close (x) button on a confirm dialog the "OK" button is triggered which is unexpected behaviour. It should trigger the cancel button.

**Comment by MohammadYounes** [comment]
I can't reproduce this, could you please provide a test case!

**Comment by NodexTech** [comment]
Sorry, it appears your documentation is wrong.

it claims this...
`` alertify.confirm(title, message, onok, oncancel);``

But if you do that then it will behave as I explained above!

**Comment by MohammadYounes** [comment]
I still unable to produce the issue you described! running the following code, works as described in the docs:

```javascript
alertify.confirm(
   'my title', 
   'my message', 
   function(){ alertify.success('confirmed');},
   function(){ alertify.error('canceled');}
);
```

You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to provide a test case.

**Comment by NodexTech** [comment]
It's fine, I've fixed it on my end by not reading the docs!

If you can't produce it then it must not be a bug
