### ISSUE TITLE
Change to or add MIT license option

### ISSUE THREAD

**Issue by buyaware-io** [MohammadYounes/AlertifyJS#240]
Dear AlertifyJS team,

May I suggest that you either add MIT license as a second option to your great library or change GPL 3.0 license completely.

Given that your work is based on MIT license component and also that is very common license for front end javascript MIT it would make sense.

Thanks,
Roman

**Comment by MohammadYounes** [comment]
@buyaware-io Thanks for the suggestion. However, I believe I'll keep the license as is.
