### ISSUE TITLE
Multiple alert boxes go away at once

### ISSUE THREAD

**Issue by HENRYMARTIN5** [MohammadYounes/AlertifyJS#241]
I have this code:
```
function doStory() {
	
        alertify.alert().setting('modal', false);
        alertify.confirm().setting('modal', false);
	alertify.alert("???", "Wake up... Please wake up...");
	alertify.alert("", "You sit up and groan.")
	alertify.alert("You", "W-where am I?");
}
document.onload(doStory());
```
And multiple alert boxes do not show up. It is just one alert box, and when you click on the ok button, it goes away, without showing any of the other alert boxes. **Help!!!**

**Comment by MohammadYounes** [comment]
@HENRYMARTIN5 The default AlertifyJS dialogs are all singletons (one instance at all times). If you want to show 2 instances of the same dialog at the same time, your dialog must be transient.

For example, you can create a new transient dialog based on alert:

``` js
    alertify.dialog('customAlert', function(){
        return { };
    },true, 'alert');
```

Sample: http://codepen.io/anon/pen/Ggaped
