### ISSUE TITLE
Auto-Dismiss Alerts

### ISSUE THREAD

**Issue by CitrusRX** [MohammadYounes/AlertifyJS#244]
Is it possible to auto dismiss an alert after x seconds? The documentation shows its possible for notifications but it doesn't seem to work with alerts.

**Comment by MohammadYounes** [comment]
@CitrusRX This functionality is available in [confirm](https://alertifyjs.com/confirm/autoCancel.html) only, you can find its implementation [here](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/confirm.js#L11-L54).
