### ISSUE TITLE
Why is impossible change anything from default options???

### ISSUE THREAD

**Issue by applibs** [MohammadYounes/AlertifyJS#246]
I would like to change option maintainFocus for example but alertify dont want accept it.
```
alertify.confirm(text, function(e) {
	// some stuff
}).setting({
	title: getLocalized("TITLE"),
	transition: "zoom",
	labels: {
		ok: getLocalized("OK"),
		cancel: getLocalized("CANCEL"),
	},
	maintainFocus: false,
});
```

I dotn want change it in source code. When maintainFocus is true then on close dialog scroll to top. When I change maintainFocus to false then it is OK as expected.

**Comment by MohammadYounes** [comment]
@applibs As mentioned in the [docs](https://alertifyjs.com/guide.html#defaults). This is a global default, not per instance.

All you need to do is:

```js
//1. This needs to be done once.
alertify.defaults.maintainFocus = false

//2. Invoke confirm
alertify.confirm(text, function(e) {
	// some stuff
}).setting({
	title: getLocalized("TITLE"),
	transition: "zoom",
	labels: {
		ok: getLocalized("OK"),
		cancel: getLocalized("CANCEL"),
	}	
});
```
