### ISSUE TITLE
alertify.notify stopped showing in safari macos

### ISSUE THREAD

**Issue by slowdownitsfine** [MohammadYounes/AlertifyJS#248]
Hello, I'm an avid user of alertify, thank you for making it!

I've noticed that recently notifications don't show up any more while on Safari in macOS. They did before and I did not change the version I was using (1.13.1). Not sure what changed in Safari.

Just wanted to let you know.

**Comment by MohammadYounes** [comment]
@slowdownitsfine Unfortunately I don't have a macOS to test on. However, I tested this on iOS Safari and notifications showed up just fine.

Thanks.

**Comment by slowdownitsfine** [comment]
When I try out the notifier on the example [page](https://alertifyjs.com/notifier.html) it will not show up for me, even in Safari on iOS.

I can confirm it worked before, but it stopped working after some update. It might be something Safari broke. I'm on the latest version of Safari.

**Comment by slowdownitsfine** [comment]
This was caused by the Hush extension. I disabled it and they show up again, sorry to bother you.
