### ISSUE TITLE
onshow only firing on second alertify.confirm() call

### ISSUE THREAD

**Issue by Moonbird-IT** [MohammadYounes/AlertifyJS#249]
Hi there,

I tried to add a custom class to an alert via the recommendations in #144 and #200 but it seems that I am doing something entirely wrong here. 

When using `.show(true, 'my-class'); ` the dialog appears but no class is being added to the dialog. 

When using `onshow(...)` the code block is only executed on the second call to alertify.confirm. Here's the code I am using:

```
alertify.confirm('Update necessary', 'The time period to be reloaded is greater than ' +
        _appConfig.durationWarnThreshold + ' hours. Reloading can take some time. Please confirm.',
        function() {
          self.generateCharts();
        }
        , function() {
          // reset to previous values
          $(_appConfig.startInput).val(moment(self.tickStart).format('YYYY-MM-DD HH:mm:ss'));
          $(_appConfig.endInput).val(moment(self.tickEnd).format('YYYY-MM-DD HH:mm:ss'));
        })
        .set({
          onshow: function() {
            this.elements.root.className += ' al-time-range';
          }
        })
        .set('labels', {
          ok: 'Reload',
          cancel: 'Reset period'
        });
```

I am using version 1.13.1.

Thanks for any pointers!

**Comment by MohammadYounes** [comment]
For `onshow` to be invoked, it must be set before showing the dialog. 

```js
// set options
alertify.confirm().set({onshow:function(){ alertify.message('on show.')}});
// show confirm
alertify.confirm('Demo');
```

**Comment by Moonbird-IT** [comment]
Thanks for the quick answer. I assumed that calling ".confirm()" would already call the function, that was infact an invocation I had never seen before. After changing the code it works like a charm, thank you!
