### ISSUE TITLE
Problems with layout CSS

### ISSUE THREAD

**Issue by dantman** [MohammadYounes/AlertifyJS#25]
The css techniques used to layout the dialog cause some problems with trying to create some types of dialogs.

Firstly,
The content area is laid out using absolute positioning. Due to this it's impossible to let a dialog's content expand vertically when you intentionally want a larger dialog. To do so the hight would have to be hardcoded.

Static/relative positioning of the content, with padding/margins to free up the space for the absolute positioned header and footer would be better.

Secondly,
```css
.alertify .ajs-body .ajs-content p { margin: 0; }
```

This ruins multi-paragraph dialogs because all spacing between them is gone. And if you've carefully tuned your `p` you can't just un-set this override, you have to explicitly override it with your default.

**Comment by MohammadYounes** [comment]
The CSS used is covering too many cases and up to now I had no problem creating any type of dialog.  It would be great If you can provide an example!

As for the `p`, this is part of the default theme (not the core CSS). which can be easily replaced.

**Comment by dantman** [comment]
![Dialog Example](http://i.imgur.com/jYgulym.png)

**Comment by dantman** [comment]
Secondary problem with the p, now that I've overridden it.

I use a technique where I have a class clear the margins from the first and last element.
```css
.ux-contentBody > :first-child { margin-top: 0; }
.ux-contentBody > :last-child { margin-bottom: 0; }
```

This allows me (in a lot of places) to have boxes where the content sits nice and nearly flush (nearly due to line-height) with the padding.

However `.alertify .ajs-body .ajs-content p` has a higher specificity meaning this doesn't work inside dialogs.

----

Ideally I wouldn't have to re-do the entire default theme, just to change a few colors and drop a p tag override.

**Comment by MohammadYounes** [comment]
I meant a code example! But it looks like this is a resizable dialog with overflow set to false.

If this is a custom dialog, you can easily set the initial height of the dialog by applying a `min-height` to the body element (inside `build` function).

**Comment by MohammadYounes** [comment]
Its hard to change it now, as it might affect others using the library. In CSS there is always a solution, you could do:

`.alertify .ajs-body .ajs-content p:not(:last-child) { padding-bottom:14px; }`

**Comment by dantman** [comment]
resizable was the default, overriding it did clean things up a bit.

**Comment by MohammadYounes** [comment]
See http://codepen.io/anon/pen/YPaQvL

**Comment by dantman** [comment]
I don't want to add more hacks. Each time I do something like that things get harder and harder.

**Comment by dantman** [comment]
What if we fork the default theme into a `basic` theme without header/footer background colours, borders, radii, text transforms, shadows, and `p` hacks. Which can be used as a base for site styled dialogs.

**Comment by MohammadYounes** [comment]
If we remove all of that, then whats left? I tried to make the default theme as much neutral as possible.

Update the codepen with your suggestion, If it does make it easier to style the dialogs, I have no problem adding it.

**Comment by dantman** [comment]
Maybe something like this?

http://codepen.io/dantman/pen/pvLwXy

**Comment by MohammadYounes** [comment]
I think its more of a modified version of the default, this one http://codepen.io/anon/pen/QwmMGN is pretty basic. Which can be added to the core CSS, because overriding these values is a must for any theme!
