### ISSUE TITLE
'alertifyjs'. CommonJS or AMD dependencies

### ISSUE THREAD

**Issue by iamade** [MohammadYounes/AlertifyJS#252]
Please I used alertify as you used it in my app but i am getting this warning below when i do ng serve

alertify.service.ts depends on 'alertifyjs'. CommonJS or AMD dependencies can cause optimization bailouts.

For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by MohammadYounes** [comment]
You can disable these warnings by adding the CommonJS module name to `allowedCommonJsDependencies` option in the `build` options located in `angular.json`  file.

```json
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
     "allowedCommonJsDependencies": [
        "alertifyjs"
     ]
     ...
   }
   ...
},
```

**Comment by iamade** [comment]
Thanks for your reply, but it is recommended that you use ECMAScript modules in your entire application. I didnt really understand what this meant, please can you help if you do.

**Comment by MohammadYounes** [comment]
You can read about modules here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

I don't know much about Angular, but I believe there should be a way to reference a library externally so it's not included in the application bundle. Thus it won't affect the size.
