### ISSUE TITLE
Correction on Guide

### ISSUE THREAD

**Issue by australopythecu** [MohammadYounes/AlertifyJS#253]
HI there, nice script, 3rd time I've implemented on a project cause I love the elegant screens with smooth transitions and styles.

Have to say that would be better to change on the home guide https://alertifyjs.com/guide.html this:

```html
<!-- include the style -->
<link rel="stylesheet" href="{PATH}/alertify.min.css" />
<!-- include a theme -->
<link rel="stylesheet" href="{PATH}/themes/default.min.css" />
 Start coding!
```

To:

```html
<!-- include the style -->
<link rel="stylesheet" href="{PATH}/css/alertify.min.css" />
<!-- include a theme -->
<link rel="stylesheet" href="{PATH}/css/themes/default.min.css" />
 Start coding!
```

As the original folder structure provide a CSS folder already.

cheers

**Comment by MohammadYounes** [comment]
Docs updated.

@australopythecu Thank you!
