### ISSUE TITLE
adjust notification size

### ISSUE THREAD

**Issue by marc-gist** [MohammadYounes/AlertifyJS#26]
Is there an easy way to adjust the notification size (width in particular)?

Thanks,

**Comment by MohammadYounes** [comment]
Yes! It's all about CSS. See http://codepen.io/anon/pen/raKYpX

**Comment by OnbitShashan** [comment]
Here a fix for if anyone using out there 
.alertify-notifier .ajs-message {
  width: max-content !important;
}

which will give you dynamic notfiers according to your title
