### ISSUE TITLE
Problems with using AlertifyJS in Ember-CLI

### ISSUE THREAD

**Issue by mikeazo** [MohammadYounes/AlertifyJS#27]
I'm trying to use AlertifyJS with Ember-CLI and couldn't get AlertifyJS to load properly. Ember-CLI currently has problems with unnamed AMD, which is how AlertifyJS is configured.

To figure out a solution to the problem, I dug through d3js code to see how it works (as it works fine with Ember-CLI). This is how d3 loads

```javascript
if (typeof define === "function" && define.amd) define(d3);
  else if (typeof module === "object" && module.exports) module.exports = d3;
  this.d3 = d3;
```

AlertifyJS, on the other hand does:

```javascript
// CommonJS
    if ( typeof module === 'object' && typeof module.exports === 'object' ) {
        module.exports = alertify;
    // AMD
    } else if ( typeof define === 'function' ) {
        define( [], function () {
            return alertify;
        } );
    // window
    } else if ( !window.alertify ) {
        window.alertify = alertify;
    }
```

Notice the difference on the AMD, d3 checks for ```define.amd``` while AlertifyJS does not. If I add that check into AlertifyJS, the third if case fires and I have access to ```window.alertify``` within my project. As a side, also doing what d3 does ```this.alertify=alertify``` works too.

I personally like the ```this.alertify=alertify``` method, but the ```window.alertify=alertify``` is workable.

**Comment by MohammadYounes** [comment]
Thanks for the details. `window` will be `this` when the context has no `window`.(see [this](https://github.com/MohammadYounes/AlertifyJS/blob/master/build/alertify.js#L3264)).

I'll add `define.amd` check soon.
