### ISSUE TITLE
Resizing window moves dialog back to center

### ISSUE THREAD

**Issue by mikeazo** [MohammadYounes/AlertifyJS#28]
Not sure if this is a bug or the desired behavior, but it is not what I expected.

When I have a dialog up and I move it to another place on the screen, then resize the window, the dialog jumps back to the center of the screen, instead of staying where I had put it. 

I have tried it in both Safari and Chrome on the first alert on [this page](http://alertifyjs.com/alert.html).

**Comment by MohammadYounes** [comment]
This is is the intended behavior, as the dialog might end up inaccessible!

**Comment by mikeazo** [comment]
Okay, after some more testing it wasn't as big of an issue as I had originally thought. I was trigging a download in a modeless dialog and at first that was triggering the resize. Turns out that only happened because I had the console open. With the console closed, triggering the download does not cause a screen resize.

**Comment by mikeazo** [comment]
Is there a way to disable this functionality? Turns out I was wrong, in Chrome, a download causes a resize event. This causes my modeless dialogs to all go back to the center of the screen.

**Comment by MohammadYounes** [comment]
To be added.

**Comment by MohammadYounes** [comment]
[`autoReset`](http://alertifyjs.com/alert.html#autoReset)  option  available as of 1.3

**Comment by mikeazo** [comment]
Works like a charm! Thanks! Great project, btw.
