### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by Torone** [MohammadYounes/AlertifyJS#29]
Hi,

It will be very nice to install it via Bower as well.

Cheers

**Comment by MohammadYounes** [comment]
Hi,

I would be happy to do that once the name **AlertifyJS** becomes available.  For now, you can use field overrides as mentioned by @fcamblor in this [comment](https://github.com/MohammadYounes/AlertifyJS/pull/19#issuecomment-70893327).

Related  #2, #14 and #15 and #19.

Thanks.

**Comment by mikeazo** [comment]
I installed via bower. ```bower install alertify-js```

**Comment by MohammadYounes** [comment]
Yes, this is the unofficial bower package created by @brunowego in #2

Thanks

**Comment by devSlike** [comment]
Maybe you make official bower package?

**Comment by MohammadYounes** [comment]
@devSlike As mentioned earlier, I would be happy to provide official bower support once the name AlertifyJS becomes available. Till the moment it is used for alertify**.**js by @bradberger

**Comment by redaxmedia** [comment]
Issue can be closed as bower is deprecated and should no longer be supported.
