### ISSUE TITLE
It should be possible to change Title

### ISSUE THREAD

**Issue by nonw** [MohammadYounes/AlertifyJS#30]
This is a great plugin, however my customers are wondering that does "AlertifyJS" mean, because this text is on each dialog and I cannot find a way to change dialog title. There should be a way to change the text in title.

**Comment by mikeazo** [comment]
Use alertify.alert('Title goes here', 'message')

**Comment by MohammadYounes** [comment]
You can set the title per dialog using the overloaded constructor that accepts a title parameter, for example `alertify.alert(title, message);` or globally by setting the default title:
```js
//Just make sure to execute this before initializing any dialog.
alertify.defaults.glossary.title = 'My Title';
```

The complete list of defaults can be found on the [Getting Started](http://alertifyjs.com/guide.html) page.
