### ISSUE TITLE
Not working correctly with float inputs

### ISSUE THREAD

**Issue by nonw** [MohammadYounes/AlertifyJS#31]
I found a tiny problem with alertify when float inputs are used on a website like this:

    select,
    textarea,
    input[type = "text"],
    input[type = "password"] {
        float: left;
        ...
    }

Then the alertify prompt box is not displayed correctly. You can easily fix this by adding just one line to your existing css code:

    .alertify .ajs-body .ajs-content .ajs-input {
        display: block;
        width: 100%;
        padding: 8px;
        margin: 4px;
        border-radius: 2px;
        border: 1px solid #CCC;
        float: none; /* this line is added */
    }

**Comment by MohammadYounes** [comment]
I believe this should handled by the website author and not this library, as it would not stop at `float`.

For example: 

    select,
    textarea,
    input[type = "text"],
    input[type = "password"] {
        position:fixed;
        ...
    }

or

    select,
    textarea,
    input[type = "text"],
    input[type = "password"] {
        color: #FFF;
        ...
    }


Thanks.
