### ISSUE TITLE
Modal dialog box

### ISSUE THREAD

**Issue by slolo2000** [MohammadYounes/AlertifyJS#33]
Hello,

It is probably a stupid question but what is the way to make a real modal dialog box?

In fact, I would like to force the user to click on a button of the dialog box to close it and avoid the closing of the dialog box when clicking outside anywhere on the screen.

The original alertify.js project has the feature.

Thanks in advance and have a nice day.

**Comment by MohammadYounes** [comment]
Hi,

Have you tried [`closableByDimmer`](http://alertifyjs.com/alert.html#closableByDimmer) option?

**Comment by slolo2000** [comment]
It works like a charm!

It was a stupid question, sorry.
Thank you very much
