### ISSUE TITLE
Showing singleton twice is not allowing resizeTo

### ISSUE THREAD

**Issue by mikeazo** [MohammadYounes/AlertifyJS#34]
Here is my [jsfiddle](http://jsfiddle.net/nwd0azdn/0/). 

In the **main** function, I am using *resizeTo* to set a custom size. The size of the dialog in that fiddle is what I expect.

In [this fiddle](http://jsfiddle.net/nwd0azdn/1/), I call the dialog twice. Notice that the size is not correct.

I tried putting the *resizeTo* in a few other places (**prepare** and a few of the hooks). I can't get it to work.

**Comment by MohammadYounes** [comment]
This is by design, when opening the same dialog again it will automatically reset size/position. If you are trying to replace the dialog contents, you could use `setContent` method. (updated [jsfiddle](http://jsfiddle.net/nwd0azdn/2/)).
