### ISSUE TITLE
Internet Explorer 8 support

### ISSUE THREAD

**Issue by slolo2000** [MohammadYounes/AlertifyJS#35]
Hello,

I try to use AlertifyJS on Internet Explorer 8 and I have the following error message:
	//copy buttons defintion
	var buttonsDefinition = [];
	if(Array.isArray(setup.buttons)){
		for(var b=0;b<setup.buttons.length;b+=1){

SCRIPT438: The object does not support the property or method « isArray »
File : alertify.js, line : 347, column : 17

Is there any way to make it works on Internet Explorer 8 or the browser will never be supported?

Thanks in advance and have a nice day.

**Comment by MohammadYounes** [comment]
Hi,

Unfortunately! IE9 and earlier will not be supported (as mentioned in the [readme](https://github.com/MohammadYounes/AlertifyJS#browser-support) - browser support for **last two versions**), If you'd like to maintain a fork with support for earlier versions? I would be happy to link to it in the [community-contribution](https://github.com/MohammadYounes/AlertifyJS#community-contribution) section.

Thanks.
