### ISSUE TITLE
Set default button

### ISSUE THREAD

**Issue by nonw** [MohammadYounes/AlertifyJS#36]
How can I change the default autofocus on buttons from "OK" to "Cancel":

    alertify.confirm("Would you like to delete this service?", function () {
        // ...
    });

I use this for delete confirmations and it's too risky if autofocus is set to "OK" by default.

**Comment by MohammadYounes** [comment]
See http://alertifyjs.com/confirm.html#defaultFocus

**Comment by nonw** [comment]
Thanks!! It works!!
