### ISSUE TITLE
how to show title (header) only?

### ISSUE THREAD

**Issue by yuomtheara** [MohammadYounes/AlertifyJS#38]
I would like to show title (header) only and set name, but not footer.

**Comment by MohammadYounes** [comment]
Something like http://alertifyjs.com/examples.html#minimal ?

**Comment by yuomtheara** [comment]
I don't want to show footer style

**Comment by MohammadYounes** [comment]
Unfortunately there is no such option! But you can customize the footer style by updating the CSS rule `.ajs-footer` to fit your needs.
