### ISSUE TITLE
how to create multiple dialog (form)?

### ISSUE THREAD

**Issue by yuomtheara** [MohammadYounes/AlertifyJS#39]
how to create multiple dialog (form)?
I read the docs too, but don't understand.
Please help me.

**Comment by MohammadYounes** [comment]
What do you mean! Can you elaborate more ?

**Comment by yuomtheara** [comment]
Multi popup, it mean that on the first alert have new btn, when I click a new btn it show the second

**Comment by MohammadYounes** [comment]
The default AlertifyJS dialogs are all singletons (one instance at all times). If you want to show 2 instances of the same dialog at the same time, your dialog must be transient.

For example, you can create a new transient dialog based on alert:
```js
    alertify.dialog('customAlert', function(){
        return { };
    },true, 'alert');
```

sample: http://codepen.io/anon/pen/Ggaped

**Comment by MohammadYounes** [comment]
I updated the codepen to also hide the footer ( #38 ):
```js
alertify.dialog('customAlert', function(){
  return {
  	hooks:{
    	onshow:function(){
      	  this.elements.footer.style.visibility = "hidden";
    	}
  	}
  };
},true, 'alert');
```

**Comment by MohammadYounes** [comment]
Closing this, but feel free to post here if you still have further questions regarding this.
