### ISSUE TITLE
how to close specific dialog of multiple?

### ISSUE THREAD

**Issue by yuomtheara** [MohammadYounes/AlertifyJS#41]
I create dialog on dialog (multiple at the same time).
And then i want to close the dialog that on current or specific.
The build in function: `alertify.closeAll()`, `alertify.alert().closeOthers()`
Please help me.

**Comment by MohammadYounes** [comment]
When you open a transient dialog, a reference to the created instance is returned. You can use it to close the dialog.

```js
var dialogs = [];
function custom(){
  dialogs.push(alertify.customAlert('<button onclick="closeLast();">Close ME</button>'));
}

function closeLast(e){
  var dialog = dialogs.shift();
  dialog && dialog.close();
}
```

[codepen](http://codepen.io/anon/pen/WbBowo)

**Comment by yuomtheara** [comment]
Very thanks, I will try

**Comment by yuomtheara** [comment]
Now don't understand `dialogs.push()`

**Comment by MohammadYounes** [comment]
Its an array to save a reference to your open dialogs, in case you just open one at a time, replace it  with a variable

```js
var dialog;
function custom(){
  dialog = alertify.customAlert('<button onclick="closeLast();">Close ME</button>');
}

function closeLast(e){
  dialog && dialog.close();
}
```

**Comment by yuomtheara** [comment]
It is clear, thanks again.

**Comment by yuomtheara** [comment]
Now problem with array of dialog have more then 2 element.
```javascript
var dialogs = [];
function custom(){
  dialogs.push(alertify.customAlert('<button onclick="closeLast();">Close ME</button>'));
  
  dialogs.push(alertify.customAlert('<button onclick="closeLast2();">Close ME 2</button>'));
}

function closeLast(e){
  var dialog = dialogs[0];
  dialog && dialog.close();
}

function closeLast2(e){
  var dialog = dialogs[1];
  dialog && dialog.close();
}
```
don't work for the second time of custom alert click.

**Comment by MohammadYounes** [comment]
2nd time you are pushing 2 new instances, You need to implement your own tracking logic!
