### ISSUE TITLE
Update less files plz

### ISSUE THREAD

**Issue by bORm** [MohammadYounes/AlertifyJS#46]
Subj

**Comment by MohammadYounes** [comment]
What do you mean?

**Comment by bORm** [comment]
Compare 
https://github.com/MohammadYounes/AlertifyJS/blob/master/src/less/alertify.less#L2
and this
https://github.com/MohammadYounes/AlertifyJS/blob/master/build/css/alertify.css#L1

where .ajs- tag in less files?

**Comment by MohammadYounes** [comment]
`.ajs-` prefix is added in the build process
https://github.com/MohammadYounes/AlertifyJS/blob/master/Gruntfile.js#L48

**Comment by bORm** [comment]
Add this please to core less filed
i`nt use Grunt

**Comment by MohammadYounes** [comment]
Unfortunately, I can't do that. It's more convenient for me to work with the none prefixed names.
