### ISSUE TITLE
open link in confirm box

### ISSUE THREAD

**Issue by Q8HMA** [MohammadYounes/AlertifyJS#51]
Hello
I want to move the user to other page it he click yes (success) and if not reshow the confirm box
thnx

      <script type="text/javascript">
         $("#labels").on( 'click', function () {
         	reset();
         	alertify.set({ labels: { ok: "Yes", cancel: "No" } });
         	alertify.confirm("Do You see the Logo ?", function (e) {
         		if (e) {
         			alertify.success("Your right");
         		} else {
         			alertify.error("Your Wrong try more time");
         		}
         	});
         	return false;
         });
      </script>

**Comment by Q8HMA** [comment]
i try this one but it not work with me


         $("#qanswer").on( 'click', function () {
         	alertify.set({ labels: { ok: "Yes", cancel: "No" } });
         	alertify.confirm("Do You see the Logo ?", function (e) {
         		if (e) {
         			alertify.success("Your right");       			
    setTimeout(function() { window.location.href("http://google.com")}, 500);
         		} else {
         			alertify.error("Your Wrong try more time");
         		}
         	});
         	return false;
         });

**Comment by MohammadYounes** [comment]
Just a few corrections and you are good to go:

  1. `set` method requires a dialog instance, you can show the dialog then set its settings or get a dialog instance using its parameter-less constructor:

    ```js
    alertify.confirm("Do You see the Logo ?").set(...);
    //or
    alertify.confirm().set(...);
    ...
    alertify.confirm("Do You see the Logo ?");
    ```

  2. `confirm` dialog uses different Ok/Cancel callbacks.

    ```js
    //3rd constructor.
    alertify.confirm(message, onok, oncancel);
    ```

That's all.

```js
$("#qanswer").on( 'click', function () {
  alertify.confirm("Do You see the Logo ?", function () {
    alertify.success("Your right");
    window.location.href = "http://alertifyjs.com/confirm.html";
  }, function(){
    alertify.error("Your Wrong try more time");
  }).set({ labels: { ok: "Yes", cancel: "No" } });
  return false;
});
```

Thanks.

**Comment by Q8HMA** [comment]
Sorry to re open it but can u make it slow do not move him fast ?

like delay 5 sec ?

thnx

**Comment by MohammadYounes** [comment]
Use a timeout like you did in your 2nd post:

```js
$("#qanswer").on( 'click', function () {
  alertify.confirm("Do You see the Logo ?", function () {
    alertify.success("Your right");
    setTimeout(function(){
      window.location.href = "http://alertifyjs.com/confirm.html";
    }, 5000);
  }, function(){
    alertify.error("Your Wrong try more time");
  }).set({ labels: { ok: "Yes", cancel: "No" } });
  return false;
});
```
