### ISSUE TITLE
What the "pinnable" for?

### ISSUE THREAD

**Issue by rabbittc** [MohammadYounes/AlertifyJS#55]
I try use `pinnable` option, but don't understand.
Please example or explain.

**Comment by MohammadYounes** [comment]
This option works only with modeless dialogs, it defines whether to show the pin button or not. 

Open the [`pinnable` option](http://alertifyjs.com/alert.html#pinnable) documentation, toggle the switch to make the script set it to true and then run the code. Now if you scroll the page, the dialog remains in place (pinned to the screen). 

Unpin the dialog by clicking the pin button in the header, and then scroll the page, the dialog will move with the document (unpinned from the screen).

If you need further clarification, let me know!
