### ISSUE TITLE
dialog callback bug?

### ISSUE THREAD

**Issue by reaganbenjaminwong** [MohammadYounes/AlertifyJS#56]
Hi,

I have 2 buttons on a page that calls the alert dialog - one has a callback function and the other doesn't.
However, the callback function is being triggered on both buttons.

OS: Windows 7 Ultimate 64bit SP1
Browser: Google Chrome - Version 42.0.2311.90 m
jsfiddle: http://jsfiddle.net/vbvhdwgo/

In the jsfiddle, there are a few buttons that on click, will show an alert dialog - some with callbacks and some without. Those without the callbacks are still triggering the callback function, with the exception of the last button, which is a workaround I'm currently using (passing in an empty callback function).

This looks like a bug to me but I may also be missing something obvious.

Thanks.

**Comment by MohammadYounes** [comment]
Hi,

Thanks for reporting this! Singleton dialogs such as the alert will preserve its options, so setting the  callback will remain intact unless explicitly removed. 

The settings API distinguishes between `get` and `set` operations by checking if the value parameter is `undefined`. This is why the 4th button was still executing the callback (this is a bug).

Sending empty callback is valid and also `null`:
```
$("#btn4").on("click", function () {
    alertify.alert("set undefined callback").set("onok", null);
});
```

I'll fix this to make `undefined` clear the callback as well.

Thanks.

**Comment by reaganbenjaminwong** [comment]
Thanks for clearing it up!

**Comment by MohammadYounes** [comment]
On second thought! I'll keep this as is, because changing it now might cause unexpected behavior to existing developers.

Appreciate your understanding. Thanks!
