### ISSUE TITLE
How to hide the prompt's Cancel button?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [MohammadYounes/AlertifyJS#57]
Great libary!
I want to show a prompt popup, hiding the "Cancel" button so the user can only press "Ok".
Is there an option for this?

    var alert = alertify.prompt();
    alert.set({
        //....  ?
    })
    alert.show();

**Comment by alessandrofrancesconi** [comment]
Something better than this?

    var alert = alertify.prompt();
        
    var cancelButton = alert.elements.footer.querySelector("button.ajs-cancel");
    hideElement(cancelButton);

    alert.set({ //....

**Comment by MohammadYounes** [comment]
You could create a new dialog that inherits from the existing `prompt` and override its [`setup()`](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/prompt.js#L51-L75) function to exclude the cancel button or override the `prepare()` function to hide it.

**Comment by alessandrofrancesconi** [comment]
Ok thanks, although I prefer to add just the two lines I wrote before, instead of rewrite a new dialog.

**Comment by MohammadYounes** [comment]
Creating a new dialog is more reusable, also hiding the button doesn't mean its not there! for instance pressing `ESC` will still trigger its action.

**Comment by alessandrofrancesconi** [comment]
Yep, sounds right.
