### ISSUE TITLE
how to set focus on alertify.dialog(...)?

### ISSUE THREAD

**Issue by yuomtheara** [MohammadYounes/AlertifyJS#58]
how to set focus on alertify.dialog(...)?
I try 
```
      setup: function () {
          return {
                focus: {
                       element : 0,
                 }
          };
```
but don't  work.

**Comment by MohammadYounes** [comment]
The element to receive default focus, has different meaning based on value type:

* `number`:     action button index.
* `string`:     querySelector to select from dialog body contents.
* `function`:   when invoked, should return the focus element.
* `DOMElement`: the focus element.
* `object`:     an object that implements `.focus()` and `.select()` functions. 

In your example, you are setting the default focus to the first action button.
