### ISSUE TITLE
Problem with "title" param in confirm and prompt?

### ISSUE THREAD

**Issue by yuomtheara** [MohammadYounes/AlertifyJS#60]
I try set `title`
```js
alertify.alert(title, message); // word fine
alertify.confirm(title, message, onok);// title don't work
alertify.prompt(title, message, value, onok);// title don't work
```
please help me.

**Comment by MohammadYounes** [comment]
The none working constructors you are mentioning do not exist! If you take another look at the docs, the [`confirm`](http://alertifyjs.com/confirm.html) dialog has the following constructors:

```js
* alertify.confirm(title, message, onok, oncancel);
 * 
 * overloads:
 *
 *  alertify.confirm(message);
 *  alertify.confirm(message, onok);
 *  alertify.confirm(message, onok, oncancel);
```

and the [`prompt`](http://alertifyjs.com/prompt.html) dialog has the following:

```js
* alertify.prompt(title, message, value, onok, oncancel);
 * 
 * overloads:
 *
 * alertify.prompt(message);
 * alertify.prompt(message, value);
 * alertify.prompt(message, value, onok);
 * alertify.prompt(message, value, onok, oncancel);
```

Thanks.

**Comment by yuomtheara** [comment]
Thanks, so I can use `alertify.confirm(title, message, function(){...}, null)` because I don't use `oncancel`.

**Comment by MohammadYounes** [comment]
Yes.

**Comment by sshokko** [comment]
Hello!

You can write sone like this

var confirm = alertify.confirm(title, message, onok);// title don't work

confirm.set({'title':'Your title'});

var prompt = alertify.prompt(title, message, value, onok);// title don't work

prompt.set({'title':'Your title'});

It works to me

**Comment by MohammadYounes** [comment]
@sshokko overloads selection is based on parameters count (not type), thus:

```js
var confirm = alertify.confirm(title, message, onok); // this matches 3-parameters constructor 
           // alertify.confirm(message, onok, oncancel);

// while 

var confirm = alertify.confirm(title, message, onok, null); //matches 4-parameters constructor 
           // alertify.confirm(title, message, onok, oncancel);

```

Thanks!

**Comment by rowej83** [comment]
> @sshokko overloads selection is based on parameters count (not type), thus:
> 
> ```js
> var confirm = alertify.confirm(title, message, onok); // this matches 3-parameters constructor 
>            // alertify.confirm(message, onok, oncancel);
> 
> // while 
> 
> var confirm = alertify.confirm(title, message, onok, null); //matches 4-parameters constructor 
>            // alertify.confirm(title, message, onok, oncancel);
> ```
> 
> Thanks!

I tried  your example for prompt with a title and I'm having the same issues as above. also, your example has a typo ( missing a comma in example after "prompt title" )

	this.$alertify.prompt("prompt title","This is prompt", "default value", (evt, value)=>
        	this.$alertify.success("ok: " + value)
        , () => this.$alertify.error("cancel")
        )

This results in just a Alertifyjs as title. Not as expected. also, the success/error do not get triggered.

**Comment by MohammadYounes** [comment]
@rowej83 

> I tried your example for prompt with a title and I'm having the same issues as above. also, your example has a typo ( missing a comma in example after "prompt title" )

I can't find the typo you mentioned ?

> This results in just a Alertifyjs as title. Not as expected. also, the success/error do not get triggered.

Prompt constructor is different than confirm, See prompt [default constructor](https://alertifyjs.com/prompt.html#usage) and [overloads](https://alertifyjs.com/prompt.html#overloads).

**Comment by rowej83** [comment]
Are you testing it your self? I literally took the example from the link you sent and it isn't working. Check this. it's not working

<a href="https://codesandbox.io/s/5y27mqm9ml">
  <img alt="Edit Vuex exercise" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

Also, the typo is on the vue-alertify instructions . you have this:
 promptWithTitle:function(){
    	this.$alertify.prompt("prompt title""This is prompt", "default value", (evt, value)=>
        	this.$alertify.success("ok: " + value)
        , () => this.$alertify.error("cancel")
        )
    }

which is missing the comma between "prompt title" and "this is prompt"

so it should be

 promptWithTitle:function(){
    	this.$alertify.prompt("prompt title","This is prompt", "default value", (evt, value)=>
        	this.$alertify.success("ok: " + value)
        , () => this.$alertify.error("cancel")
        )
    }

**Comment by MohammadYounes** [comment]
@rowej83 

> Also, the typo is on the vue-alertify instructions . you have this:

I didn't write any vue instruction ?

**Comment by MohammadYounes** [comment]
@rowej83 Ah, seems you confused this with the Vue wrapper [repo](https://github.com/sj82516/vue-alertify#how-to-use). 

Based on the wrapper code, you should use [`promptWithTitle`](https://github.com/sj82516/vue-alertify/blob/master/src/index.js#L40) instead, see updated fork of your sample

[![Edit Vuex exercise](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oo23v06j35)

I see the typo in the [README](https://github.com/sj82516/vue-alertify#how-to-use), You may notifier the author about it by opening an issue over there.

Thanks.

**Comment by rowej83** [comment]
> @rowej83 Ah, seems you confused this with the Vue wrapper [repo](https://github.com/sj82516/vue-alertify#how-to-use).
> 
> Based on the wrapper code, you should use [`promptWithTitle`](https://github.com/sj82516/vue-alertify/blob/master/src/index.js#L40) instead, see updated fork of your sample
> 
> [![Edit Vuex exercise](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/oo23v06j35)
> 
> I see the typo in the [README](https://github.com/sj82516/vue-alertify#how-to-use), You may notifier the author about it by opening an issue over there.
> 
> Thanks.

Sorry, I did mistaken it for another repo. I added issues on that repo.

**Comment by thearabbit** [comment]
Good for `Vue AlertifyJS`!
