### ISSUE TITLE
Reset default config

### ISSUE THREAD

**Issue by jonaswebdev** [MohammadYounes/AlertifyJS#63]
Hi,

How I can reset default config?

Because I set a label for button for alert (modal), eg "OKEY", and run it, Alertify will show alert with "OKEY" button.

After, I run again this method but without set label for button and Alertify will show alert with "OKEY" again, the Alertify should be get default value? eg: alertify.defaults.glossary.ok

Thanks

**Comment by MohammadYounes** [comment]
The built-in dialogs are all singletons, so they maintain their config values. May be an option to reset all config values or a method to destroy the dialog would be a good enhancement! I'm open to suggestions.

Thanks.

**Comment by nilemarbarcelos** [comment]
Found this when dealing with the same problem when trying to use confirm dialogs with different button classes (alertly.defaults.themes.ok), was able to solve it by using the factories and setting transient to false though.

**Comment by MohammadYounes** [comment]
As of 1.5.0 you can call [`destroy`](http://alertifyjs.com/alert.html#destroy) method. which will close the dialog, delete it's DOM and reset all settings to initial state.
