### ISSUE TITLE
How to attach 'Submit, Other btn' of "Meteor autoForm" to footer??

### ISSUE THREAD

**Issue by thearabbit** [MohammadYounes/AlertifyJS#67]
I create custom alertify and pass the `autoForm` of `Meteor` like this
```js
<template name="addressInsert">
    {{#autoForm collection=Sample.Collection.Address id="addressInsert" type="insert"}}

        {{> afQuickField name='name'}}

        <button type="submit" class="btn btn-primary"> Save</button>
        <button type="button" class="btn btn-default"> Other</button>
    {{/autoForm}}
</template>
```
So I want to attach the `submit, other btn` to alertify footer and then use any `Autoform Hook`, `other btn` template event.
Please help me.

**Comment by MohammadYounes** [comment]
You can access the footer div using `elements.footer`,  are you using a custom dialog or a built-in one ?

**Comment by thearabbit** [comment]
I use custom like this:
```js
createNewAlertify = function (names) {

    var alerts = _.isArray(names) ? names : [names];

    _.each(alerts, function (element) {

        var name = element;

        if (!alertify[name]) {
            alertify.dialog(name, function () {
                return {
                    setup: function () {
                        return {
                            options: {
                                maximizable: true,
                                closableByDimmer: false,
                                resizable: false,
                                transition: "zoom"
                            }
                        };
                    },
                    prepare: function () {
                        this.elements.footer.style.visibility = "hidden";
                    }
                };
            }, false, 'alert');
        }

    });

};
```

**Comment by MohammadYounes** [comment]
In this case don't hide the footer, just clear it's contents and append your buttons to it. I will be able to assist you better if you could provide an online sample.

**Comment by thearabbit** [comment]
Sorry, I want to hidden the default footer, but want to attach the `submit, other btn`  of `autoform`.

**Comment by MohammadYounes** [comment]
Would you provide an online sample to work on!

**Comment by thearabbit** [comment]
Excuse me, I missing to reply.
I use `Auto Form Package` in `Meteor`, so I can't use default button footer of `alertifyjs`.
I render the form to custom `alertifyjs`.
```js
<template name="addressInsert">
    {{#autoForm collection=Sample.Collection.Address id="addressInsert" type="insert"}}

        {{> afQuickField name='name'}}

        <button type="submit" class="btn btn-primary"> Save</button>
        <button type="button" class="btn btn-default"> Other</button>
    {{/autoForm}}
</template>
```
![2016-02-15_17-48-55](https://cloud.githubusercontent.com/assets/4495160/13046693/ecba6756-d40c-11e5-907c-5a178c368c20.png)
Would to add style footer like this
![2016-02-15_17-51-45](https://cloud.githubusercontent.com/assets/4495160/13046704/fbc9f7ac-d40c-11e5-8619-03c9200cccc2.png)

**Comment by MohammadYounes** [comment]
Creating a sample online would be great, you can start here http://codepen.io/anon/pen/raohK

Is the form submitted via script ? If yes, you can move them to the primary buttons placeholder inside your custom dialog ?

```js
    prepare:function(){
        $(this.elements.body).find('.btn').appendTo(this.elements.buttons.primary);
    },
```

**Comment by thearabbit** [comment]
My form submitted via `form submit`.
Now I tried
```js
// custom
prepare: function () {
	this.setContent(this.message);
	this.elements.footer.style.visibility = "hidden";
},

// auto form
...........
<div class="ajs-footer">
	<div class="ajs-auxiliary ajs-buttons"></div>
	<div class="ajs-primary ajs-buttons">
		<button type="submit" class="btn btn-primary">{{fa "floppy-o"}} Save</button>
		<button type="reset" class="btn btn-default">{{fa "refresh"}} Reset</button>
	</div>
</div>
```
It show

![2016-02-15_19-53-39](https://cloud.githubusercontent.com/assets/4495160/13049237/1288507c-d41e-11e5-916e-fb1264edeae8.png)

I thinks that I should be remove the current of `this.elements.footer.style.visibility` (no hidden).
Please help me.

**Comment by MohammadYounes** [comment]
Since you don't requires resize function, use display none insead.

```js
this.elements.footer.style.display = "none";
```

**Comment by thearabbit** [comment]
Now it work fine.
But have some problem with `css space`

![2016-02-15_21-05-25](https://cloud.githubusercontent.com/assets/4495160/13050807/64487d38-d428-11e5-9b40-16c03398d016.png)

Very thanks for your helping :+1:

**Comment by MohammadYounes** [comment]
If your form has it's own padding, simply disable [`padding`](http://alertifyjs.com/confirm/padding.html) option.
