### ISSUE TITLE
how to remove alertifyjs name from dialog

### ISSUE THREAD

**Issue by BernardA** [MohammadYounes/AlertifyJS#69]
Hello
Your app seems to be cool enough, but I'd rather not have its name popup before my visitors each time an alert is issued ( I prefer my name to be shown, of course)

How to replace the name on the dialog box?

Thanks

**Comment by BernardA** [comment]
Never mind, I found it.

Regards
Bernard

**Comment by MohammadYounes** [comment]
Thanks!

> duplicate #30

**Comment by BernardA** [comment]
Thanks for your reply. Actually I had found where to change the title on your script. Your response gives it more flexibility.

Regards
Bernard
