### ISSUE TITLE
Support for IE 8

### ISSUE THREAD

**Issue by ala-musleh** [MohammadYounes/AlertifyJS#70]
I have found some issues with IE 8
first Array.isArray() is not supported
/* if (Array.isArray(setup.buttons)) */
fixed it by adding this function
(function () {
    if (typeof Array.isArray === "undefined") {
        Array.isArray = function (obj) {
            return Object.prototype.toString.call(obj) === "[object Array]";
        };
    }
}());

second in removeAbsPositionFix(instance)
marginTop and marginLeft is NaN
fixed
(isNaN(marginTop) ? 0 : marginTop)
(isNaN(marginLeft) ? 0 : marginTop)

after fixing these errors the confirm alert shows but it make the background black

**Comment by MohammadYounes** [comment]
You need to consider using `filter` attribute as IE8 does not support `opacity`.

Unfortunately! IE9 and earlier will not be officially supported (as mentioned in the [readme](https://github.com/MohammadYounes/AlertifyJS#browser-support) - browser support for **last two versions**), If you'd like to maintain a fork with earlier versions support? I would be happy to link to it in the [community-contribution](https://github.com/MohammadYounes/AlertifyJS#community-contribution) section.
