### ISSUE TITLE
How to prevent pop off

### ISSUE THREAD

**Issue by AngryCrotch** [MohammadYounes/AlertifyJS#71]
How to prevent pop off， thank you . i
![image](https://cloud.githubusercontent.com/assets/631400/9727722/73a2bab8-5634-11e5-94f5-876d16251e48.png)

**Comment by MohammadYounes** [comment]
As mentioned in the [factory documentation](http://alertifyjs.com/factory.html), setting the cancel property to true on the event object prevents the dialog from closing.

```js
callback:function(closeEvent){
  //The closeEvent has the following properties
  //
  // index: The index of the button triggering the event.
  // button: The button definition object.
  // cancel: When set true, prevent the dialog from closing.
}
```

Thanks.

**Comment by AngryCrotch** [comment]
thank you  !
