### ISSUE TITLE
Set Title seems not to work

### ISSUE THREAD

**Issue by Ganbin** [MohammadYounes/AlertifyJS#73]
According to the doc : 
/*
 * @title {String or DOMElement} The dialog title.
 * @message {String or DOMElement} The dialog contents.
 * @onok {Function} Invoked when the user clicks OK button.
 * @oncancel {Function} Invoked when the user clicks Cancel button or closes the dialog.
 *
 * alertify.confirm(title, message, onok, oncancel);
 * 
 * overloads:
 *
 *  alertify.confirm(message);
 *  alertify.confirm(message, onok);
 *  alertify.confirm(message, onok, oncancel);
 *
 */  

We should be able to set the title of the confirm like this : alertify.confirm('Title','Message');

But when we do this, we get as result, a confirm dialog with 'AlertifyJS' as title and 'Title' as the message.

**Comment by Ganbin** [comment]
alertify.confirm('Message').set('title','Title');

This is the way I achieve to set the title But this will set the title for all the next opened confirm dialog.

**Comment by MohammadYounes** [comment]
Calling `alertify.confirm('title', 'message')` will use the second overload `alertify.confirm(message, onok);`.

The only constructor to set both message and title requires both `onok` and `oncancel` callbacks: `alertify.confirm(title, message, onok, oncancel);`

The confirm dialog is a singleton, and all set options will be preserved, including the title.

**Comment by Ganbin** [comment]
Ok thank you for the quick answer.
