### ISSUE TITLE
not able to replicate example Button-Less Generic Dialog 

### ISSUE THREAD

**Issue by BernardA** [MohammadYounes/AlertifyJS#75]
Hello
I've have implemented alertify.js and it's working fine as far as regular alerts and prompts are concerned.

Now I want expand its use to include passing on some information and even a form dialog.

It's very much like the example  Button-Less Generic Dialog from http://alertifyjs.com/examples.html, only that is not a login form, but rather a message form.

In any case I have not been able to figure out  where to place the html for #loginForm.

I can place it anywhere with <body>, but if I put a css:display:none; it will not show on the dialog.

Please advise on how to handle the html portion.

Much appreciated.

Bernard

**Comment by MohammadYounes** [comment]
Hello,

Try to wrap it in a container and place `display:none` on the container, thus your form will be visible once viewed in the dialog, or you can remove the `display:none` after adding the element to the dialog. 

Thanks.

**Comment by MohammadYounes** [comment]
If you inspect the source of the examples page, you can see the form wrapped in a display none container:

![generic](https://cloud.githubusercontent.com/assets/4712046/10033538/c1c67130-6192-11e5-8673-713242310d75.png)

**Comment by BernardA** [comment]
Hello
Thank you very much for your quick and concise reply. I somehow missed the set up as I reviewed the example. Sorry for that.

Regards
Bernard
