### ISSUE TITLE
Always jumps to the top of the page in IE

### ISSUE THREAD

**Issue by huhubun** [MohammadYounes/AlertifyJS#76]
Hi,

This is a wonderful plugin. However, I noticed one of the behaviors in IE is inconsistent with that in Chrome. After the Modal pops up in IE, the browser will automatically jump to the top of the page. Such behavior never happens in Chrome.
I noticed that Changes in  #49 used  `window.scrollX` and `window.scrollY` which is not supported in IE.
If `saveScrollPosition()` can be changed to the code below, all browsers including IE will have consistent behavior.

```javascript
function saveScrollPosition() {
    scrollX = window.scrollX || document.documentElement.scrollLeft;
    scrollY = window.scrollY || document.documentElement.scrollTop;
}
```

or use the `getScrollLeft()`, `getScrollTop()` method that is already in your plugin

```javascript
function saveScrollPosition() {
    scrollX = getScrollLeft();
    scrollY = getScrollTop();
}
```

Hope this helps. Thanks.

**Comment by MohammadYounes** [comment]
To be released in the next batch.

:+1:   Thanks!
