### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by stoivo** [MohammadYounes/AlertifyJS#77]
I was looking for `modal` on your homepage and it took me a while. I was searching for `Dimmer`. Could you add a line on documentation that this is to remove the Dimmer. That how same me some time next time.

Other than that, I enjoy Alertify.JS so much

**Comment by MohammadYounes** [comment]
docs updated (see http://alertifyjs.com/alert.html#modal)

Thanks.

**Comment by stoivo** [comment]
Thanks :sparkles:

I know this is kind of irretating, but I want this package to get known :smile:
