### ISSUE TITLE
Reset Confirm buttons after change labels

### ISSUE THREAD

**Issue by serdarde** [MohammadYounes/AlertifyJS#78]
After I change confirm labels for a dialog, if I use confirm once again in same page, buttons should reset.

For exmple even on your page after you click change label example and then the other ones the labels stay like I customized them.

I add 2 pictures from your page to show it.

![first](https://cloud.githubusercontent.com/assets/6826944/10793115/c6734e38-7d8f-11e5-8378-c3c2c0fda9b0.png)

![then](https://cloud.githubusercontent.com/assets/6826944/10793116/c67bb08c-7d8f-11e5-8d51-224d71d0ec82.png)

as you can see, labels havent resetted theirselves

I m sorry because of bad English ;) 

thanks

**Comment by MohammadYounes** [comment]
Hello,

The built-in dialogs are all singletons, so they maintain their config values. you can call [`destroy`](http://alertifyjs.com/alert.html#destroy) method. which will close the dialog, delete it's DOM and reset all settings to initial state.

Thanks.

> #63

**Comment by serdarde** [comment]
hi mohammad,

I started to use "destroy" after each alert box like this:

                onclose: function () {
                    alertify.alert().destroy();
                }


it didnt help. then I started to use "destroy" before each alertfy shown like this:

alertify.alert().destroy();
alertify.alert(login.translations.update_fail);

unfortunately it didnt help too and after that my browser started to frezee :-1:

and I receive that error: 'too much recursion'

my browser is: firefox 43.0.3 

Thanks for your attention

**Comment by MohammadYounes** [comment]
Hi, I tried this http://jsfiddle.net/2gpqqdmy/ and no freezing! re-check your code, may be something else is causing it?

**Comment by MohammadYounes** [comment]
@serdarde  Moreover, `destroy` calls `close` internally (see [here](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/dialog/dialog.js#L370-L382)), which will cause an infinite recursion. I suspect you still have `onclose` calling `destroy` some where in your code.

**Comment by serdarde** [comment]
yeah you are right, I found it! :+1: and now no more freezing but still it doesnt get back frames and etc. I mean 'destory' doesnt make settings defaults.

I am using angularjs but I am not sure if it has a sense about it.

**Comment by MohammadYounes** [comment]
Would be helpful if you could create a test case online! Anyway, I'll recheck this tomorrow.

**Comment by MohammadYounes** [comment]
@serdarde Apologies for the delay, I tested `destroy` method and every thing is reset to default! If you could provide an online test case presenting the issue!

Thanks.

**Comment by ovidiugabriel** [comment]
Hello, 

I think you should reopen this issue.

```js
// At some point I am doing
var labels = {ok: 'I accept the risk!', cancel: 'Back to safety!'};
alertify.confirm('Here be dragons!', dialogMessage, function () {
   // ...
}).set('labels', labels).set('defaultFocus', 'cancel');

// Then on a button click I am doing

alertify.confirm().destroy();
alertify.confirm(title, msg, function() {
    // ...
}).set('labels', {ok: 'Da', cancel: 'Renunta'});

```

Unfortunately I could not manage to reset the labels to initial defaults neither to set them with new values.
For the second dialog the first set of labels is still used.

**Comment by ovidiugabriel** [comment]
> @serdarde Apologies for the delay, I tested `destroy` method and every thing is reset to default! If you could provide an online test case presenting the issue!
> 
> Thanks.

Can you please post an example on how we can reset labels to default values?

**Comment by MohammadYounes** [comment]
> Can you please post an example on how we can reset labels to default values?

@ovidiugabriel here is an example http://jsfiddle.net/61b9Ltau/ of changing labels, then destroying the alert and showing it again (note labels were reset).

>How can we test if there is an alertify object that needs to be destroyed?

Builtin dialogs are all singletons, only one instance is available at all times, so doing `alertify.alert().destroy()` is sufficient. For transient dialogs, you need to track them yourself. 

Thanks.

**Comment by serdarde** [comment]
Hi @MohammadYounes that was years ago and now I do not have the examples anymore. Your example looks quite well. We can close the issue

**Comment by ovidiugabriel** [comment]
Thanks!

Yes, it works.  Calling `alertify.alert().destroy()` multiple times does not have any harmful effect.
