### ISSUE TITLE
AlertifyJS with Tampermonkey

### ISSUE THREAD

**Issue by BitteWenden** [MohammadYounes/AlertifyJS#81]
I'm injecting my own JavaScript on a page with Tampermonkey. I wanted to use AlertifyJS on that page to create some dialogs. The problem is that when I create a dialog in my JavaScript, the dialog is shown but I can't move it (it always goes back to it's original position) and I can't close it, it reopens itself again. If I create a dialog over the console it works though.

Any idea what could cause that or any idea how to fix that?

**Comment by MohammadYounes** [comment]
Never used Tampermonkey before, but have you tried the nsafeWindow retrieval setting: https://tampermonkey.net/faq.php?ext=dhdg#Q404 ?

**Comment by BitteWenden** [comment]
I can't find that setting anywhere, I guess they removed it.

**Comment by BitteWenden** [comment]
Fixed, the problem was on my side. Sorry!

**Comment by MohammadYounes** [comment]
So it had nothing to do with window context ?

**Comment by MohammadYounes** [comment]
No worries!  Thanks for the feedback.
