### ISSUE TITLE
Moving dialog off screen can cause issues

### ISSUE THREAD

**Issue by mikeazo** [MohammadYounes/AlertifyJS#82]
Here is my [jsfiddle](http://jsfiddle.net/7acmL09b/) and an animated image.

![alertify](https://cloud.githubusercontent.com/assets/6683518/11252685/7d3a448e-8e05-11e5-9019-b7ca89e376c7.gif)

As you can see, I can move the dialog off the screen, then I can't move it back or close it.

Is there a good way to handle this?

**Comment by MohammadYounes** [comment]
Re-sizing the window will reset the dialog position, and pressing ESC key would close it.

May be I add an option to prevent the dialog from going off-screen ?

**Comment by mikeazo** [comment]
If adding that option is possible, that would be awesome. In my use case ESC and resizing won’t do the trick.

**Comment by MohammadYounes** [comment]
To be added, Thanks!

**Comment by MohammadYounes** [comment]
New option [`moveBounded`](http://alertifyjs.com/alert/moveBounded.html) available as of 1.6 

Thanks!
