### ISSUE TITLE
Move docpad-plugin-paged to devDependencies

### ISSUE THREAD

**Issue by hackwaly** [MohammadYounes/AlertifyJS#83]

**Comment by MohammadYounes** [comment]
Ops! committed by mistake, it's not even used :)

Thanks!

**Comment by MohammadYounes** [comment]
It's removed now, is it affecting you on npm or can it wait till next update ?

**Comment by hackwaly** [comment]
I can wait for next update

**Comment by MohammadYounes** [comment]
Thanks!
