### ISSUE TITLE
Not full documentation

### ISSUE THREAD

**Issue by AntonZelinsky** [MohammadYounes/AlertifyJS#85]
You have not full documentation. For example, the function **alertify.prompt** has the definition of 
```javascript
alertify.prompt(title, message, value, onok, oncancel);
```
 which is not in the documentation.
Also
```javascript
alertify.confirm(title, message, onok, oncancel);
alertify.alert(title, message, onok);
```

**Comment by MohammadYounes** [comment]
They are listed in the default usage, the first constructor (just before the overloads).

May be I should re-write the default usage pages!

Thanks.
