### ISSUE TITLE
Setting overflow: false - does not work

### ISSUE THREAD

**Issue by kolengri** [MohammadYounes/AlertifyJS#89]
Hello, this setting "overflow: false" does not work.
On your website in documentation is the same problem http://alertifyjs.com/alert/overflow.html
Safari 9.0.3

**Comment by MohammadYounes** [comment]
Hi, Would you provide a test case ?

**Comment by MohammadYounes** [comment]
You may also check the youtube example http://alertifyjs.com/examples.html#youtube

**Comment by MohammadYounes** [comment]
Closing due to lack of info.
