### ISSUE TITLE
close() vs destroy()?

### ISSUE THREAD

**Issue by thearabbit** [MohammadYounes/AlertifyJS#90]
I use `alertifyjs` in `Meeteor` with `Auto Form`.
I always `.close()` when the form is success.
So, I should use `.destroy()` too or not.
```js
// custom
alertify.exchange().close();

--------- OR -------------

alertify.exchange().close();
alertify.exchange().destroy();
```

**Comment by MohammadYounes** [comment]
[`.close()`](http://alertifyjs.com/alert/close.html) simply closes the dialog, it's settings/DOM will remain intact (you can simply call [`.show()`](http://alertifyjs.com/alert/show.html) to reopen it). 

On the other hand, [`.destroy()`](http://alertifyjs.com/alert/destroy.html) closes the dialog, deletes the associted DOM and reset all of its settings to default.

Thanks!

**Comment by thearabbit** [comment]
Thanks for your quick reply.
