### ISSUE TITLE
Notify always on top

### ISSUE THREAD

**Issue by darkice32** [MohammadYounes/AlertifyJS#93]
The css class alertify-notifier has a default z-index of 1982 but this should be the most largest value to always show the notify message on top.

**Comment by MohammadYounes** [comment]
It's simply a default, you can override the value to accommodate your application requirements!

**Comment by darkice32** [comment]
I already have done that but thought it could be better to give it a higher value so that I do not have to make adjustments [ lazy :) ]

**Comment by MohammadYounes** [comment]
I see :)  I'll consider it in the next major version.

Thanks!
