### ISSUE TITLE
Request : reverseButtons

### ISSUE THREAD

**Issue by seltix5** [MohammadYounes/AlertifyJS#94]
hi,

geat job btw!

I have a simple request : add the "reverseButtons" setting on the defaults :

    var defaults = {
        reverseButtons:false,
        ....

and on the instance set :

instance.set('reverseButtons', setup.options.reverseButtons === undefined ? alertify.defaults.reverseButtons : setup.options.reverseButtons);

this way its possible to change the settings to all instances...

thank you.

**Comment by MohammadYounes** [comment]
Hi,

The defaults contains options shared by all dialogs, This option is specific to `confirm`/`prompt`.

Moreover, they are singletons and you only need to set it once and it will be applied to all instances.

Thanks!

**Comment by MohammadYounes** [comment]
Also you may use `.ajs-button { float: right; }` which would reverse the buttons, but won't reverse the tab order.

**Comment by seltix5** [comment]
hi,

this could be a shared option, when multiple buttons are available ofc.

i was initiating the script like this :

	jQuery(function($){
		alertify.defaults["modal"] = true;
		alertify.defaults["basic"] = false;
                ...

but il will just add :

	alertify.confirm().set("reverseButtons", true); 
	alertify.prompt().set("reverseButtons", true); 

it was just a idea =)

**Comment by MohammadYounes** [comment]
Shared options are implemented by the dialog factory, this one is implemented [inside](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/confirm.js#L143-L149) the dialog it self.

Using `alertify.confirm().set("...` is much better =)

Thanks!
