### ISSUE TITLE
How to enable/disable buttons in Alertify Dialog

### ISSUE THREAD

**Issue by neel5481** [MohammadYounes/AlertifyJS#96]
Hi ,

I have created on Alertify dialog with "Dialog factory".
I have created two buttons in the setup function as below.
```js
setup:function() {
            return {
              buttons:[{ text: "OK", key: 27, className: "btn btn-primary" },
                       { text: "Cancel", key: 27, className: "btn btn-primary" }],
              options: { modal: 0, resizable: true }
            };
```
Now i want to enable/disable the button depending on the contents of the dialog.
How to enable/disable the buttons of the alertify dialog ?

Thanks

**Comment by MohammadYounes** [comment]
Hi,

You can access any given button element via the internal buttons array:
```js
// Each created button will be saved with the button definition inside buttons collection
// this.__internal.buttons[x].element
```

For example, you could toggle the buttons in your prepare method:

```js
prepare:function(){
  // this.__internal.buttons[x].element
}
```

Thanks!

**Comment by neel5481** [comment]
Thank you Mohammad for the quick response.
I am able to enable/disable the buttons.

**Comment by MohammadYounes** [comment]
Great, Thanks for the feedback!
