### ISSUE TITLE
Multiple custom dialogs - unable to change content of only one specific instance

### ISSUE THREAD

**Issue by RaulButuc** [MohammadYounes/AlertifyJS#98]
I have tried to create multiple custom dialogs within the same view. Once two or more custom dialogs have been created, they remain bound to the page. So now, I have a list of custom dialogs existing in the background, with at most one open at any given point in time.

The issue lies in the fact that if I want to keep some different content in each of them I simply can't tell the dialogs to implement that behaviour since there is no way to do so. Having used the `prepare` function does not help, since this modifies _all_ instances of alertify. There is no unique ID for each instance, and this leads to further problems when used with other frameworks such as TagIt (which works only for the _first_ instance where it appears). I would normally expect each dialog to have that unique ID that can be used to call for changes to be made only to one dialog, and not to all of them.

In my case, the `prepare` function to loads the data. This means that _all_ my alertify instances from the background get their content replaced with the content I intend to use for _one_ of those instances. Having an instance of TagIt within my dialog content, and since TagIt will work only for the _first_ instance that it appears in, I am unable to use that framework unless I somehow find a way to attach a unique ID to each dialog.

So is there any way around this? Or was the dialog system not designed to support multiple custom dialogs with different content?

**Comment by RaulButuc** [comment]
I managed to produce a temporary fix this by using raw jQuery to remove all instances that are hidden before creating a new one.

```javascript
$('.ajs-hidden').each(function () {
        $(this).remove();
    });
```

**Comment by MohammadYounes** [comment]
AlertifyJS provides 2 types of dialogs, singletons and transient (multi-instance). Singleton instances are tracked by the library and are accessible via the parameter-less constructor of the dialog, i.e. `instance = alertify.mySingletonDialog();` 

Transient dialogs are not tracked, however, you get a reference to each created instance upon invocation. i.e. `instance = alertify.myTransientDialog(args);`. The DOM inside the dialog, is separate from AlertifyJS and is totally controlled by you. 

I'm a bit confused, and would like to know whether you have singletone or transient dialogs implemented ?

**Comment by MohammadYounes** [comment]
Moreover, what is the fix for ?
> I managed to produce a temporary fix by using raw jQuery to remove all instances that are hidden before creating a new one.

**Comment by RaulButuc** [comment]
I am not talking about singleton and multi-instance. I am talking about a list of _different_ types of objects:
`alertify.myFirstType();` `alertify.mySecondType();` etc. I have a list such as this, and whenever the `prepare` function is loaded for one of them, all the others have their contents changed, because there is no unique identifier.

**Comment by MohammadYounes** [comment]
The `prepare` function is not shared across instances! Would you create a sample online ?  You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started.

**Comment by RaulButuc** [comment]
I'm afraid my project is written in ASP.NET MVC 5 and the prepare method uses `$.get()` to request the partial views with their assigned models. Not sure if I can reproduce that.

**Comment by MohammadYounes** [comment]
Anything that simulate your case would be a great starting point for me to understand the underlying issue.

**Comment by RaulButuc** [comment]
Sure, I'll try to get something similar on jsfiddle.

**Comment by RaulButuc** [comment]
Sorry, the problem was with the code in the `prepare`. I wasn't sure how to update the content, and I completely overlooked this part while debugging. I wrote this:

```javascript
$.get("profile/remove-company/" + profileRemoveCompanySlug, function (data) {
    $(".ajs-content").html(data); // this was the issue
});
```

**Comment by MohammadYounes** [comment]
Thanks for the feedback! So issue resolved ?

**Comment by RaulButuc** [comment]
Yes. Sorry again for wasting your time with this. And thanks for the response. :)

**Comment by MohammadYounes** [comment]
No problem :)
