### ISSUE TITLE
notify not working

### ISSUE THREAD

**Issue by Bluscream** [MohammadYounes/AlertifyJS#99]
When i try a alertify.notify thing it just returns a object in the dev console.

![Screenshot](http://i.imgur.com/EKuqcbz.png)

**Comment by MohammadYounes** [comment]
Have you included AlertifyJS CSS files ?

**Comment by Bluscream** [comment]
Yes, with Javscript.

**Comment by Bluscream** [comment]
i believe it has something to do with the z-index.

**Comment by MohammadYounes** [comment]
You can increase the default notifier [z-index](https://github.com/MohammadYounes/AlertifyJS/blob/master/build/css/alertify.css#L820)  by overriding the [`.alertify-notifier`](https://github.com/MohammadYounes/AlertifyJS/blob/master/build/css/alertify.css#L816-L823) class:

```css
.alertify-notifier {
  z-index: 99999;
}
```

**Comment by Bluscream** [comment]
I tried that until i got a number way higher then yours, but it does not take any effect.

**Comment by Bluscream** [comment]
Oh sry wrong button :D

**Comment by MohammadYounes** [comment]
Would you provide an online sample?

**Comment by Bluscream** [comment]
I tried it in the official Discord client as BetterDiscord plugin.

**Comment by MohammadYounes** [comment]
I need a link to see the exact issue!

**Comment by MohammadYounes** [comment]
Join me [here](https://gitter.im/MohammadYounes/AlertifyJS)

**Comment by Bluscream** [comment]
Issue solved; mixed up libraries :o

**Comment by MohammadYounes** [comment]
Thanks for the feedback!
